- lib/provider/camunda/element-templates/parts/CustomProps.js
I'm creating my own properties panel in React with element template support. It is backed by these core getters and setters. `getPropertyValue` is already exported whilst `setPropertyValue` is not. This just exports the setter so it can be used directly if needed.
> Export setPropertyValue from element templates helpers

- styles/groups.less
This pull request removes a CSS rule that has no obvious benefits and results in hidden entries if there are a lot of them.
Related to #282
Support: https://app.camunda.com/jira/browse/SUPPORT-5085
> fix(styles): do not restrict container height

- lib/provider/camunda/CamundaPropertiesProvider.js
* Add a hint that a user task's BPMN id maps to the Task Definition Key in the Java API.
> feat(usertask): add hint about task definition key

- lib/factory/EntryFactory.js
- lib/provider/bpmn/parts/EventProps.js
- lib/provider/bpmn/parts/implementation/CompensateEventDefinition.js
- lib/provider/bpmn/parts/implementation/ConditionalEventDefinition.js
- lib/provider/bpmn/parts/implementation/ErrorEventDefinition.js
- lib/provider/bpmn/parts/implementation/EscalationEventDefinition.js
- lib/provider/bpmn/parts/implementation/MessageEventDefinition.js
- lib/provider/bpmn/parts/implementation/SignalEventDefinition.js
- lib/provider/bpmn/parts/implementation/TimerEventDefinition.js
- lib/provider/camunda/element-templates/parts/ChooserProps.js
- lib/provider/camunda/element-templates/parts/CustomProps.js
- lib/provider/camunda/parts/ConditionalProps.js
- lib/provider/camunda/parts/ListenerDetailProps.js
- lib/provider/camunda/parts/ScriptTaskProps.js
- lib/provider/camunda/parts/ServiceTaskDelegateProps.js
- lib/provider/camunda/parts/VariableMappingProps.js
- lib/provider/camunda/parts/implementation/Callable.js
- lib/provider/camunda/parts/implementation/CandidateStarter.js
- lib/provider/camunda/parts/implementation/Delegate.js
- lib/provider/camunda/parts/implementation/External.js
- lib/provider/camunda/parts/implementation/InputOutputParameter.js
- lib/provider/camunda/parts/implementation/Script.js
- use "translate" where it is available
- Script.js changed to accept "translate" as an input parameter of exported function
- Changed 3 places, which used the "Script.js", so that the "translate" module passed as a parameter down to function as a parameter value
- Listener.js - refactored, so that translation would be obtained on rendering, not on module loading.  Language switching would work correctly that way.
Closes https://github.com/bpmn-io/bpmn-js-properties-panel/issues/297
> Localize literals, which are not yet localized.

- lib/helper/CategoryHelper.js
- lib/provider/bpmn/BpmnPropertiesProvider.js
- lib/provider/bpmn/parts/NameProps.js
- lib/provider/bpmn/parts/implementation/Name.js
- lib/provider/camunda/CamundaPropertiesProvider.js
- test/spec/provider/bpmn/ElementName.bpmn
- test/spec/provider/bpmn/ElementNameSpec.js
Fixes #278 
* Show correct name-labels for `bpmn:TextAnnotation` (Text) and `bpmn:Group` (Category Value)
* Make `bpmn:CategoryValue` for `bpmn:Group` editable in properties panel
* Initializes `bpmn:CategoryValue` if needed, via `CategoryHelper` (depends on  https://github.com/bpmn-io/bpmn-js/pull/1040)
> Show correct name properties

- lib/helper/InputOutputHelper.js
- test/spec/helper/InputOutputHelperSpec.js
The Input Output tab should not be shown for Gateways, it does not make sense from the engine perspective. 
Closes https://github.com/bpmn-io/bpmn-js-properties-panel/issues/221
> fix(helper): disallow inputOutput on bpmn:Gateway

- lib/provider/camunda/parts/ListenerDetailProps.js
Related to camunda/camunda-modeler#1517
We don't cover the other event types in separate test cases, so I think the current tests are covering this one as well.
> feat(camunda): add update event to task listener

- karma.conf.js
- package-lock.json
- package.json
This PR fixes our broken CI pipeline (promises are not supported by default in phantom-js, the latest bpmn-js version requires promises).
We'll get rid of callback deprecation warning logs in CI output with #329.
> Promise polyfill for phantom-js

- package-lock.json
- package.json
- test/TestHelper.js
- test/helper/index.js
- test/spec/provider/camunda/element-templates/CreateHelperSpec.js
- test/spec/provider/camunda/element-templates/parts/Helper.js
Closes #329 
This PR bumps bpmn-js to v7.0.1 and fixes the deprecation warnings in tests.
> Bump bpmn-js to v7.0.1

- lib/PropertiesPanel.js
- lib/factory/AutoSuggestTextBoxFactory.js
- lib/factory/EntryFactory.js
- lib/provider/camunda/parts/implementation/InputOutputParameter.js
- styles/_variables.less
- styles/properties.less
- test/TestHelper.js
- test/spec/factory/AutoSuggestTextBoxFactorySpec.js
- test/spec/provider/camunda/InputOutputParameterTextSpec.js
Integrates auto-suggest textbox into Input & Output Parameter. The suggestion will be triggered once you start typing an expression or the cursor is inside an expression, cf. expression brackets "${}".
[Example Diagram](https://github.com/bpmn-io/bpmn-js-properties-panel/files/5199462/diagram_autosuggest.bpmn.txt)
Closes #345 
> Autosuggest Component

- lib/factory/AutoSuggestTextBoxFactory.js
To ensure descriptions for auto-suggest textboxes got wrapped with the `[data-show]` we have to create it inside the wrapper.
_No issue_
> fix(auto-suggest): create description field inside show-wrapper

- styles/groups.less
With https://github.com/bpmn-io/bpmn-js-properties-panel/commit/f53fd5c890dd90b3624574d9c71e9199c3596658 we introduced the `group-header` selector, which is also used in `div` elements. Therefore the bug results because all `div` elements got hidden on the toggle. This fixes this behavior.
Closes #373
> fix(styles): prevent hiding group-headers

- lib/provider/camunda/element-templates/parts/DescriptionProps.js
- test/spec/provider/camunda/element-templates/parts/DescriptionProps.bpmn
- test/spec/provider/camunda/element-templates/parts/DescriptionProps.json
- test/spec/provider/camunda/element-templates/parts/DescriptionPropsSpec.js
Properly retrieve event definition from template.
Related to https://github.com/camunda/camunda-modeler/issues/1990
> fix(element-templates): correct removal of event template

- .travis.yml
- package-lock.json
- package.json
- test/TestHelper.js
This removes the `bpmn-font` dependency that is not needed anymore, as the required assets are inlined / shipped with bpmn-js.
> deps: remove bpmn-font dependency

- lib/provider/camunda/parts/implementation/ProcessVariables.js
- test/spec/provider/camunda/ProcessVariablesSpec.js
* We used the variable name as an identifier for the items inside the process variable overview
* These can include unescaped content
--> Prevent this by using generic ids + escape variable name whenever used
Related to camunda/camunda-modeler#2031
> fix(process-variables): prevent using variable names as identifier

- lib/provider/bpmn/BpmnPropertiesProvider.js
- lib/provider/bpmn/parts/IdProps.js
- lib/provider/bpmn/parts/NameProps.js
- lib/provider/camunda/CamundaPropertiesProvider.js
- test/spec/provider/bpmn/ProcessParticipantCollapsedSpec.js
- test/spec/provider/bpmn/ProcessParticipantExpandedSpec.js
- test/spec/provider/bpmn/ProcessParticipantSpec.js
This PR adds a "participant-" prefix to the input labels defining the name and id of a participant in the properties panel.
Closes #327 (again)
> Add 'participant-' prefix to name and id inputs for clarity

- lib/provider/camunda/element-templates/Validator.js
- test/spec/provider/camunda/element-templates/ElementTemplatesLoaderSpec.js
- test/spec/provider/camunda/element-templates/ValidatorSpec.js
fix upstream camunda/camunda-modeler#2111
fix upstream camunda/camunda-modeler#2038 (duplication by accident)
> fix(element-templates): always log id and name with validation error

- lib/PropertiesPanel.js
- test/spec/PropertiesPanelSpec.js
This implements a tab provider mechanism similar to the one we bpmn-js uses for palette and context pad.
---
Required by https://github.com/camunda/camunda-modeler/issues/1992.
> Support multiple tab providers

- lib/provider/camunda/element-templates/CustomElementsPropertiesActivator.js
- lib/provider/camunda/element-templates/Validator.js
- lib/provider/camunda/element-templates/cmd/ChangeElementTemplateHandler.js
- lib/provider/camunda/element-templates/parts/CustomProps.js
- lib/provider/camunda/element-templates/util/handleLegacyScopes.js
- test/spec/provider/camunda/element-templates/ValidatorSpec.js
- test/spec/provider/camunda/element-templates/cmd/ChangeElementTemplateHandlerSpec.js
- test/spec/provider/camunda/element-templates/cmd/service-task-connector-template-1.json
- test/spec/provider/camunda/element-templates/fixtures/error-scopes-properties-missing.json
- test/spec/provider/camunda/element-templates/fixtures/error-scopes-property-invalid.json
- test/spec/provider/camunda/element-templates/fixtures/error-scopes-type-missing.json
- test/spec/provider/camunda/element-templates/fixtures/scopes-array.json
- test/spec/provider/camunda/element-templates/fixtures/scopes-single-connector.json
- test/spec/provider/camunda/element-templates/parts/CustomProps.bpmn
- test/spec/provider/camunda/element-templates/parts/CustomProps.json
- test/spec/provider/camunda/element-templates/parts/CustomPropsSpec.js
- test/spec/provider/camunda/element-templates/util/handleLegacyScopesSpec.js
This allows the new format for scopes inside element templates.
```js
{
"name": "My Template",
"id": "com.example.template",
"version": 1,
"appliesTo": [
"bpmn:ServiceTask"
],
"properties": [],
"scopes": [
{
"type": "camunda:Connector",
"properties": [ ]
]
}
```
It also ensures backward compatibility for old `camunda:Connector` scopes.
```js
{
"name": "My Template",
"id": "com.example.template",
"version": 1,
"appliesTo": [
"bpmn:ServiceTask"
],
"properties": [],
"scopes": {
"camunda:Connector": {
"properties": [ ]
}
}
```
Closes #423
> Element Templates Scopes v2

- lib/provider/bpmn/parts/implementation/ElementReferenceProperty.js
- lib/provider/bpmn/parts/implementation/ErrorEventDefinition.js
- lib/provider/bpmn/parts/implementation/EventDefinitionReference.js
- lib/provider/camunda/CamundaPropertiesProvider.js
- lib/provider/camunda/parts/ErrorsProps.js
- lib/provider/camunda/parts/implementation/ErrorEventDefinition.js
- lib/provider/camunda/parts/implementation/Errors.js
- lib/provider/camunda/parts/implementation/ErrorsEntries.js
- package-lock.json
- package.json
- styles/properties.less
- test/spec/provider/camunda/ErrorsProps.bpmn
- test/spec/provider/camunda/ErrorsPropsSpec.js
Related to camunda/camunda-modeler#2070
This PR adds the UI component of the `camunda:ErrorEventDefinition` elements in the properties panel, in the input/output tab.
2 missing features to note :
-Copying and pasting a service task with a camunda:ErrorEventDefinition that references a bpmn:Error doesn't apply the reference on paste.
-Changing the type of a service task with camunda:ErrorEventDefninitions won't delete them, just hide the errors group in the input/output tab
Those features will be added at a later stage.
> Add errors group to input output tab

- lib/provider/camunda/element-templates/CreateHelper.js
- lib/provider/camunda/element-templates/Validator.js
- lib/provider/camunda/element-templates/cmd/ChangeElementTemplateHandler.js
- test/spec/provider/camunda/element-templates/ValidatorSpec.js
- test/spec/provider/camunda/element-templates/cmd/ChangeElementTemplateHandlerSpec.js
- test/spec/provider/camunda/element-templates/cmd/error-template-1.json
- test/spec/provider/camunda/element-templates/cmd/service-task-error.bpmn
- test/spec/provider/camunda/element-templates/fixtures/error-templates.json
This PR adds
* support for creating scoped `bpmn:Error` bindings
* support for applying `camunda:ErrorEventDefinition` bindings
* support for handling template `camunda:ErrorEventDefinition` --> `bpmn:Error` references
This adds **not**
* proper validation for `camunda:ErrorEventDefinition` (cf. missing binding.errorRef)
* display `camunda:ErrorEventDefinition` bindings in the Properties Panel custom props (get and set values)
* default components for  `camunda:ErrorEventDefinition` 
* docs updates
as this shall be part of https://github.com/bpmn-io/bpmn-js-properties-panel/issues/424.
-----
Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/424
Closes https://github.com/bpmn-io/bpmn-js-properties-panel/issues/425
> Error Templates (Part 1)

- package-lock.json
- package.json
Fixes a peer dependency problem with `@bpmn-io/extract-process-variables` & `camunda-bpmn-moddle`
> chore: bump @bpmn-io/extract-process-variables

- lib/provider/camunda/CamundaPropertiesProvider.js
- lib/provider/camunda/element-templates/CreateHelper.js
- lib/provider/camunda/element-templates/Helper.js
- lib/provider/camunda/element-templates/Validator.js
- lib/provider/camunda/element-templates/cmd/ChangeElementTemplateHandler.js
- lib/provider/camunda/element-templates/parts/CustomProps.js
- lib/provider/camunda/element-templates/parts/ErrorsProps.js
- package-lock.json
- package.json
- test/spec/provider/camunda/element-templates/CreateHelperSpec.js
- test/spec/provider/camunda/element-templates/ValidatorSpec.js
- test/spec/provider/camunda/element-templates/cmd/ChangeElementTemplateHandlerSpec.js
- test/spec/provider/camunda/element-templates/cmd/service-task-error.bpmn
- test/spec/provider/camunda/element-templates/cmd/task.bpmn
- test/spec/provider/camunda/element-templates/fixtures/error-bindings-invalid.json
- test/spec/provider/camunda/element-templates/parts/CustomProps.bpmn
- test/spec/provider/camunda/element-templates/parts/CustomProps.json
- test/spec/provider/camunda/element-templates/parts/CustomPropsSpec.js
- test/spec/provider/camunda/element-templates/parts/ErrorsProps.bpmn
- test/spec/provider/camunda/element-templates/parts/ErrorsProps.json
- test/spec/provider/camunda/element-templates/parts/ErrorsPropsSpec.js
This adds
* support for `camunda:errorEventDefinition` & `bpmn:error` scope bindings in the Custom Fields
* the template errors default component
* bump the supported JSON Schema version to `v0.3.0`
Closes #424 
Related to https://github.com/camunda/camunda-modeler/issues/2083
-----
This can be tested with the following templates: [my-templates.json.txt](https://github.com/bpmn-io/bpmn-js-properties-panel/files/6162720/my-templates.json.txt)
I will send an artifact via Slack, because `build-on-demand` does not provide nested dependency as of now.
> Error Template Props

- CHANGELOG.md
- lib/helper/AsyncCapableHelper.js
- lib/helper/ExtensionElementsHelper.js
- lib/helper/FormHelper.js
- lib/helper/ImplementationTypeHelper.js
- lib/helper/InputOutputHelper.js
- lib/provider/camunda/parts/FormProps.js
- lib/provider/camunda/parts/VariableMappingProps.js
- lib/provider/camunda/parts/implementation/Callable.js
- lib/provider/camunda/parts/implementation/FieldInjection.js
- test/spec/provider/camunda/FieldInjectionSpec.js
- test/spec/provider/camunda/ImplementationTypeSpec.js
- test/spec/provider/camunda/InputOutputParameterListSpec.js
- test/spec/provider/camunda/InputOutputParameterMapSpec.js
- test/spec/provider/camunda/InputOutputParameterScriptSpec.js
- test/spec/provider/camunda/InputOutputParameterTextSpec.js
- test/spec/provider/camunda/InputParametersSpec.js
- test/spec/provider/camunda/ListenerFieldInjectionSpec.js
- test/spec/provider/camunda/OutputParametersSpec.js
- test/spec/provider/camunda/PropertiesCollaborationSpec.js
- test/spec/provider/camunda/PropertiesSpec.js
- test/spec/provider/camunda/RetryTimeCycleSpec.js
This PR cleans up the `getExtensionElements` helper, making it return `[]` instead of `undefined` for empty extension elements, to avoid unnecessary checks, and updates every usage of it in the properties panel.
This will be a breaking change for next version, for anyone importing it, namely zeebe.
> Return an empty array instead of undefined when querying empty extension elements

- lib/provider/camunda/parts/implementation/ImplementationType.js
- test/spec/provider/camunda/ImplementationType.bpmn
- test/spec/provider/camunda/ImplementationTypeSpec.js
This PR adds a condition that removes all `camunda:ErrorEventDefinition` extensions when changing the implementation type of a service task from external to any other.
Closes #441
> Remove error event definitions when changing service task implementation type

- lib/provider/camunda/element-templates/Validator.js
- package-lock.json
- package.json
- test/spec/provider/camunda/element-templates/ElementTemplatesLoaderSpec.js
- test/spec/provider/camunda/element-templates/ValidatorSpec.js
- test/spec/provider/camunda/element-templates/parts/CustomProps.json
- test/spec/provider/camunda/element-templates/util/validateSpec.js
This (partly) replaces the existing `PropertiesPanel#Validator` functionality with our `element-templates-json-schema`. This means that we now
* Validate `property.type` <-> `property.binding.type` combinations (Note that this needs an update of [our documentation](https://github.com/camunda/camunda-modeler/tree/develop/docs/element-templates#bindings), since beforehand, we did not strictly enforce those combinations, but informed possible errors)
* Keep the validation of versioning and schema compatibility inside the original Validator
* Move all other validation to the Schema itself
I decided to keep the existing test cases to have another verification, although most of them only test the existing JSON Schema.
----
Requires https://github.com/camunda/element-templates-json-schema/pull/27 …
> feat(element-templates): validate templates via JSON Schema

- CHANGELOG.md
- lib/provider/camunda/element-templates/Validator.js
- package-lock.json
- package.json
- test/spec/provider/camunda/element-templates/ValidatorSpec.js
This uses the pre-compiled validator + schema: https://github.com/bpmn-io/element-templates-validator
* no more compiling on runtime, prevents CSP errors in the Modeler distro
* reduced bundle size
* the validator now defines with schema version we're using
Related to camunda/camunda-modeler#2181
> fix(element-templates): use pre-compiled schema validator

- lib/provider/bpmn/parts/DocumentationProps.js
- test/spec/provider/bpmn/Documentation.bpmn
- test/spec/provider/bpmn/DocumentationSpec.js
This PR changes our documentation behavior to more sensible defaults:
* we pick the first documentation element that has a
textFormat=text/plain (or an empty text format)
* we update the documentation entry rather than resetting
the whole list of entries
This ensures we play more nicely with others, that may use multiple
documentation entries for different use cases.
Related to https://github.com/camunda/camunda-modeler/issues/1682
> feat: update existing documentation entries

- lib/factory/TableEntryFactory.js
- test/spec/provider/camunda/PropertiesSpec.js
> fix: give properties table inputs a unique identifier

- lib/PropertiesPanel.js
Fix verified through manual test since we [can't unit test it](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/test/spec/PropertiesPanelSpec.js#L507).
Related to camunda/camunda-modeler#2280
> fix: preserve Windows newline characters

- lib/provider/camunda/element-templates/CreateHelper.js
- package-lock.json
- package.json
- test/spec/provider/camunda/element-templates/CreateHelperSpec.js
- test/spec/provider/camunda/element-templates/ValidatorSpec.js
- test/spec/provider/camunda/element-templates/cmd/ChangeElementTemplateHandlerSpec.js
- test/spec/provider/camunda/element-templates/cmd/call-activity-template-1.json
fixes upstream camunda/camunda-modeler#2334
requires camunda/element-templates-json-schema#30
(Note that prior to releasing this, we need to bump the
element-templates-json-schema version - otherwise respective schemas
will be marked as invalid and ignored)
> feat(element-templates): support specific local camunda:in|out

- src/provider/zeebe/ZeebePropertiesProvider.js
- test/spec/provider/zeebe/ZeebePropertiesProvider.spec.js
Required by camunda/camunda-modeler#2586
> fix(zeebePropProvider): rename target group to calledElement

- test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider.spec.js
This adds a test case to verify our layout config feature we don't actively promote yet, but use internally. It's possible to pre-define the `open` state of certain groups with it. Example:
```js
import BpmnModeler from 'bpmn-js/lib/Modeler';
const modeler = new BpmnModeler({
container: '#canvas',
propertiesPanel: {
parent: '#properties',
layout: {
groups: {
'general': { open: true },
'documentation': { open: false },
'CamundaPlatform__UserAssignment': { open: true }
}
}
}
});
```
> test(camunda-platform): add test case to verify layout config

- CHANGELOG.md
- rollup.config.js
This is a concise update of the changelog which will prepare us for the first alpha. It will be followed by updated examples and the blog post which we should have ready before the first stable release.
> chore(CHANGELOG): update to v1.0.0-alpha.0

- test/distro/distroSpec.js
Some of the dependencies expose only ESModules and this is causing
problems unless we instrument rollup to bundle the deps with
the library. This, however, leads to increased bundle size
which doesn't give any benefit as modern bundlers can handle
commonjs/esmodules interop.
> rewrite distro test

- src/render/BpmnPropertiesPanel.js
- src/render/BpmnPropertiesPanelRenderer.js
- test/spec/BpmnPropertiesPanel.spec.js
- test/spec/BpmnPropertiesPanelRenderer.spec.js
* there's no use case for removing the root element without immediately adding another one or destroying the diagram so destroying the properties panel on every root.removed isn't necessary
* attach on diagram.init
* detach on diagram.destroy
* render on root.added
* update on root.added
---
Related to https://github.com/camunda/camunda-modeler/issues/2374
> Update Properties Panel Instead of Destroying on New Root Element

- package-lock.json
- package.json
- src/provider/element-templates/components/PropertyDescription.js
- src/provider/element-templates/properties/CustomProperties.js
- src/provider/element-templates/properties/InputProperties.js
- src/provider/element-templates/properties/OutputProperties.js
- src/provider/element-templates/util/sanitize.js
- test/spec/provider/element-templates/properties/CustomProperties.description.json
- test/spec/provider/element-templates/properties/CustomProperties.spec.js
- test/spec/provider/element-templates/properties/InputProperties.json
- test/spec/provider/element-templates/properties/InputProperties.spec.js
- test/spec/provider/element-templates/properties/OutputProperties.json
- test/spec/provider/element-templates/properties/OutputProperties.spec.js
- test/spec/provider/element-templates/util/sanitize.spec.js
Closes #547 
Closes #375 
This uses the same `preact-markup` and sanitization setup as we already use in `form-js`. I checked out the Sanitizer and believe we can safely use the rules as we have with our Markdown support in form-js, I don't see a need for specific rules in properties panel land. We already sanitize pretty carefully over there.
After a chat with @MaxTru I decided to keep it simple for now and only bring back the [HTML support for element template field descriptions](https://github.com/camunda/camunda-modeler/blob/develop/docs/element-templates/README.md#defining-template-properties). The introduction of `preact-markup` would allow us to do even crazier things as a core feature, e.g. using markdown / HTML to provide my custom properties - instead of the existing JSX syntax. …
> Render HTML descriptions for Element Templates

- src/provider/element-templates/components/PropertyDescription.js
- test/spec/provider/element-templates/properties/CustomProperties.description.json
- test/spec/provider/element-templates/properties/CustomProperties.spec.js
Follow up of #549 
> I've found a problem within the templates example. There's a description with `undefined` as the content.
> 
> ![image](https://user-images.githubusercontent.com/28307541/150386479-a8a1fd76-b37b-421a-b3a8-be85537c673c.png)
_Originally posted by @barmac in https://github.com/bpmn-io/bpmn-js-properties-panel/issues/549#issuecomment-1017721031_
> fix(element-templates): do not render empty descriptions

- rollup.config.js
Closes #550
This ensures `preact-markup` uses our delivered version of `preact` when using it in downstream projects.
> fix(rollup): exclude `preact-markup` from external dependencies

- README.md
We did use the old import until now.
The one documented works at `bpmn-js-properties-panel@next`.
> docs: correct usage in README

- package-lock.json
- package.json
- src/provider/element-templates/properties/CustomProperties.js
- test/spec/provider/element-templates/Validator.spec.js
- test/spec/provider/element-templates/fixtures/complex.bpmn
- test/spec/provider/element-templates/fixtures/complex.json
- test/spec/provider/element-templates/fixtures/error-groups-missing-id.json
- test/spec/provider/element-templates/fixtures/groups.json
- test/spec/provider/element-templates/properties/CustomProperties.groups.bpmn
- test/spec/provider/element-templates/properties/CustomProperties.groups.json
- test/spec/provider/element-templates/properties/CustomProperties.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/2673
This needs https://github.com/camunda/element-templates-json-schema/pull/39 to be released + integrated.
This adds the basic grouping feature for C7 element templates.
> C7 Template groups

- src/provider/cloud-element-templates/CreateHelper.js
- src/provider/cloud-element-templates/cmd/ChangeElementTemplateHandler.js
- src/provider/cloud-element-templates/properties/CustomProperties.js
- test/spec/provider/cloud-element-templates/cmd/ChangeElementTemplateHandler.spec.js
- test/spec/provider/cloud-element-templates/cmd/task-template-optional.json
- test/spec/provider/cloud-element-templates/fixtures/complex.bpmn
- test/spec/provider/cloud-element-templates/fixtures/complex.json
- test/spec/provider/cloud-element-templates/properties/CustomProperties.bpmn
- test/spec/provider/cloud-element-templates/properties/CustomProperties.json
- test/spec/provider/cloud-element-templates/properties/CustomProperties.spec.js
Closes #559 
Script to try it out
```sh
npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel#559-optional-inputs-outputs -c "npm run start:cloud-templates"
```
> Optional `zeebe:input` and `zeebe:output`

- src/provider/bpmn/properties/NameProps.js
- test/spec/provider/bpmn/NameProps.bpmn
- test/spec/provider/bpmn/NameProps.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/2333
Changing our approach for this one, reasons for which are detailed here: https://github.com/bpmn-io/bpmn-moddle/pull/91
> fix: disable NameProps on DataAssociations

- .github/workflows/CI.yml
- package-lock.json
- package.json
- src/provider/bpmn/properties/NameProps.js
- test/TestHelper.js
- test/spec/BpmnPropertiesPanelRenderer.spec.js
- test/spec/PanelHeaderProvider.spec.js
- test/spec/provider/camunda-platform/ProcessVariablesProps.spec.js
> fix: remove import of non-existing API

- src/provider/element-templates/components/ElementTemplatesGroup.js
Just a minor fix I stumbled upon using templates in the Camunda Modeler:
Probably introduced during a find&replace.
> chore(ElementTemplatesGroup): correct select title

- package.json
Without it, we would get warnings on `npm install`
```sh
npm WARN bpmn-js-properties-panel@1.0.0-alpha.4 requires a peer of @bpmn-io/properties-panel@0.10.x but none is installed. You must install peer dependencies yourself.
```
> deps: mark properties-panel@0.11 as peer dependency

- src/provider/zeebe/ZeebePropertiesProvider.js
- src/provider/zeebe/properties/FormProps.js
- test/spec/provider/zeebe/Forms.bpmn
- test/spec/provider/zeebe/Forms.spec.js
Related to camunda/camunda-modeler#2759
> feat(cloud): allow setting custom form key

- src/contextProvider/zeebe/DescriptionProvider.js
Add doc links for Multi-Instance and Assignment Groups:
closes #600
> feat(DescriptionProvider): add user and multi-instance task links

- package-lock.json
- package.json
- rollup.config.js
- src/provider/cloud-element-templates/Validator.js
- src/provider/element-templates/Validator.js
Semver does not properly bundle with rollup as it contains cyclic dependencies:
This PR replaces semver with semver-compare. Also shaves off 9kB (minified) of the bundled distribution.
> Semver compare

- src/provider/cloud-element-templates/ElementTemplates.js
- src/provider/cloud-element-templates/util/templateUtil.js
- src/provider/element-templates/ElementTemplates.js
- src/provider/element-templates/util/templateUtil.js
- test/spec/provider/cloud-element-templates/ElementTemplates.spec.js
- test/spec/provider/element-templates/ElementTemplates.spec.js
This allows us to use the `elementTemplate` service to apply templates without caring about the implementation details, i.e. if it is a Platform or Cloud template.
Mid-term this will also support our "element templates everywhere" spirit (cf. [`bpmn-io/bpmn-js-connectors-extension#apply-template-usage`](https://github.com/bpmn-io/bpmn-js-connectors-extension/compare/apply-template-usage)).
---
Related to https://github.com/bpmn-io/element-template-chooser/issues/2#issuecomment-1067806835.
Required by https://github.com/bpmn-io/element-template-chooser/issues/2
> feat: add `ElementTemplates#applyTemplate` API

- package.json
Installing the properties panel with the latest libraries will otherwise fail; we already test with the respective library.
> deps: bump `@bpmn-io/properties-panel` peer dependency to `0.12.x`

- package-lock.json
- package.json
Follow up of https://github.com/bpmn-io/extract-process-variables/issues/17
This also removes the annoying missing peer-deps warnings.
> deps: update to `@bpmn-io/extract-process-variables@v0.4.5`

- src/render/PanelHeaderProvider.js
- test/spec/PanelHeaderProvider.spec.js
Closes #610
Displays the element template name as element type in the properties panel header.
Script to try it out
```sh
npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel#610-template-name-header -c "npm run start:cloud-templates"
```
> feat(render): display template name in header

- src/provider/cloud-element-templates/properties/CustomProperties.js
- src/provider/element-templates/properties/CustomProperties.js
- test/spec/provider/cloud-element-templates/properties/CustomProperties.spec.js
- test/spec/provider/element-templates/properties/CustomProperties.spec.js
Try it out with `npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel#618-element-template-sections -c 'npm run start:cloud-templates'`
closes #618 
Applying a `entriesVisible` template can open other groups. This is a bug that was present before, I created https://github.com/bpmn-io/bpmn-js-properties-panel/issues/620 to track it
> feat(element-templates): open custom groups

- src/provider/zeebe/properties/CalledDecisionProps.js
> fix(zeebe): mark CalledDecision.id as `feel: optional`

- package-lock.json
- package.json
- src/hooks/index.js
- src/hooks/useService.js
- src/hooks/useShowCallback.js
- src/provider/bpmn/properties/ErrorProps.js
- src/provider/bpmn/properties/MessageProps.js
- src/provider/zeebe/properties/BusinessRuleImplementationProps.js
- src/provider/zeebe/properties/CalledDecisionProps.js
- src/provider/zeebe/properties/MessageProps.js
- src/provider/zeebe/properties/MultiInstanceProps.js
- src/provider/zeebe/properties/TargetProps.js
- src/provider/zeebe/properties/TaskDefinitionProps.js
- src/render/BpmnPropertiesPanel.js
- test/spec/hooks/useShowCallback.spec.js
- test/spec/provider/bpmn/ErrorProps.spec.js
- test/spec/provider/bpmn/MessageProps.spec.js
- test/spec/provider/zeebe/BusinessRuleImplementationProps.spec.js
- test/spec/provider/zeebe/CalledDecisionProps.spec.js
- test/spec/provider/zeebe/MessageProps.bpmn
- test/spec/provider/zeebe/MessageProps.spec.js
- test/spec/provider/zeebe/MultiInstanceProps.bpmn
- test/spec/provider/zeebe/MultiInstanceProps.spec.js
- test/spec/provider/zeebe/TargetProps.bpmn
- test/spec/provider/zeebe/TargetProps.spec.js
- test/spec/provider/zeebe/TaskDefinitionProps.bpmn
- test/spec/provider/zeebe/TaskDefinitionProps.spec.js
Adds `show` callbacks to all entries that can be shown through events. A `useShowCallback` hook is introduced to simplify things.
List of errors: https://docs.google.com/spreadsheets/d/1AbFn2lXWPywmM1OaP7pVZUaAG0CglYv-2th2dbl5_k4/edit#gid=0
---
Requires https://github.com/bpmn-io/properties-panel/pull/142
> Be Able to Show Entry and Error through Event

- CHANGELOG.md
* `FEAT`: add show callbacks to show entries and errors ([#601](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/601))
* `FEAT`: open element template custom groups ([#621](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/621))
* `FEAT`: display template name in header ([#627](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/627))
* `FEAT`: add documentation ref to header ([#629](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/629))
* `FIX`: copy versioned element template ([#632](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/632))
* `FIX`: use correct business object ([#634](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/634))
* `FIX`: mark called decision ID as optionally FEEL …
> chore(CHANGELOG): update to v1.0.0-alpha.9

- rollup.config.js
The latest release is broken due to us using inherits (that uses Node shim per default): [https://github.com/bpmn-io/bpmn-js-properties-panel/compare/v1.0.0-alpha.8...v1.0.0-alpha.9#diff-8656a2b322b6384fe4e47[…]e4056bcc4915b2d6b34d7e630R1](https://github.com/bpmn-io/bpmn-js-properties-panel/compare/v1.0.0-alpha.8...v1.0.0-alpha.9#diff-8656a2b322b6384fe4e47cfa32ed42103d62f39e4056bcc4915b2d6b34d7e630R1).
The solution to this is to tell rollup to not use the node shim, but use inherits browser version: https://github.com/bpmn-io/bpmn-js/blob/develop/rollup.config.js#L100.
> chore: ensure we use <browser> deps, if provided

- rollup.config.js
- src/provider/cloud-element-templates/ReplaceBehavior.js
- src/provider/element-templates/ReplaceBehavior.js
Usage of `inherits` was introduced without installing https://www.npmjs.com/package/inherits dependency. Thus, the Node.js internal `inherits` was used which is not being polyfilled when bundling. Instead of installing the dependency the usage of `inherits` can be avoided altogether.
> Do not use `inherits`

- CHANGELOG.md
* `FIX`: do not use `inherits` ([#645](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/645))
* `FIX`: use `browser` field of dependencies before falling back to `module` and `main` ([#646](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/646))
> chore(CHANGELOG): update to v1.0.0-alpha.10

- src/render/PanelHeaderProvider.js
- test/spec/PanelHeaderProvider.spec.js
Closes #635
Depends on #641 (to work end-to-end)
> feat(render): display template icons in header

- assets/element-templates.css
Little follow up of https://github.com/bpmn-io/bpmn-js-properties-panel/pull/650#issuecomment-1087381293
> style: object fit on template icons

- test/spec/BpmnPropertiesPanelRenderer.spec.js
It just makes sense to have it for C7 templates as well.
> test(templates): add template chooser to C7 templates test

- package-lock.json
- package.json
- test/spec/provider/camunda-platform/AsynchronousContinuationsProps.bpmn
- test/spec/provider/camunda-platform/AsynchronousContinuationsProps.spec.js
- test/spec/provider/camunda-platform/DmnImplementationProps.spec.js
- test/spec/provider/camunda-platform/FormDataProps.bpmn
- test/spec/provider/camunda-platform/FormDataProps.spec.js
- test/spec/provider/camunda-platform/FormField.bpmn
- test/spec/provider/camunda-platform/FormField.spec.js
- test/spec/provider/camunda-platform/FormTypeProps.spec.js
- test/spec/provider/camunda-platform/ImplementationProps.spec.js
- test/spec/provider/camunda-platform/ImplementationTypeProps.spec.js
- test/spec/provider/camunda-platform/InputProps.bpmn
- test/spec/provider/camunda-platform/InputProps.spec.js
- test/spec/provider/camunda-platform/JobExecutionProps-Process.bpmn
- test/spec/provider/camunda-platform/JobExecutionProps.spec.js
- test/spec/provider/camunda-platform/OutputProps.bpmn
- test/spec/provider/camunda-platform/OutputProps.spec.js
- test/spec/provider/zeebe/AssignmentDefinitionProps.bpmn
- test/spec/provider/zeebe/AssignmentDefinitionProps.spec.js
- test/spec/provider/zeebe/BusinessRuleImplementationProps.bpmn
- test/spec/provider/zeebe/BusinessRuleImplementationProps.spec.js
- test/spec/provider/zeebe/OutputPropagationProps.bpmn
- test/spec/provider/zeebe/OutputPropagationProps.spec.js
Adds integration tests for https://github.com/camunda/camunda-bpmn-js-behaviors.
---
Related to https://github.com/bpmn-io/internal-docs/issues/404
> Add Behavior Integration Tests

- src/provider/cloud-element-templates/cmd/ChangeElementTemplateHandler.js
- test/spec/provider/cloud-element-templates/ElementTemplates.bpmn
- test/spec/provider/cloud-element-templates/ElementTemplates.spec.js
- test/spec/provider/cloud-element-templates/cmd/ChangeElementTemplateHandler.spec.js
- test/spec/provider/cloud-element-templates/cmd/task-definition.bpmn
- test/spec/provider/cloud-element-templates/cmd/task-headers.bpmn
- test/spec/provider/cloud-element-templates/cmd/task-input-output.bpmn
- test/spec/provider/cloud-element-templates/cmd/task-template-1-hidden.json
- test/spec/provider/cloud-element-templates/fixtures/integration.bpmn
- test/spec/provider/cloud-element-templates/fixtures/integration.json
> fix(cloud-templates): keep exisiting configuration after apply

- src/provider/zeebe/properties/CalledDecisionProps.js
Fixes https://github.com/camunda/camunda-modeler/issues/2725
> fix: called decision decision ID made explicit

- src/provider/camunda-platform/properties/FormField.js
> fix: focus form field enum value on create

- package-lock.json
- package.json
- src/provider/camunda-platform/properties/ProcessVariablesProps.js
- test/spec/provider/camunda-platform/ProcessVariablesProps-collaboration.bpmn
- test/spec/provider/camunda-platform/ProcessVariablesProps-process.bpmn
- test/spec/provider/camunda-platform/ProcessVariablesProps.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3003
> Add separator to process variable sources 

- README.md
Replace `import CamundaExtensionModule from 'camunda-bpmn-moddle/lib',` to `import CamundaExtensionModule from 'camunda-bpmn-moddle/lib';`
> fix(docs): "Use with Camunda properties" error

- package-lock.json
- package.json
- test/TestHelper.js
- test/fixtures/a11y.bpmn
- test/spec/BpmnPropertiesPanelRenderer.spec.js
Adds a basic integration test to validate against a defines a11y ruleset ([via axe](https://github.com/dequelabs/axe-core)). I simply added the same rule definitions as we use [for the component tests](https://github.com/bpmn-io/properties-panel/pull/132) in `@bpmn-io/properties-panel`.
Disclaimer: this does not guarantee an accessible properties panel, but at least make sure we continuously track basic a11y issues in a more advanced example (groups are open, nested lists are open). 
----
Slack time work. I will talk about this in one of the next weeklies.
> test(a11y): add basic test scenario

- package-lock.json
- package.json
- src/provider/element-templates/util/templateUtil.js
- src/render/BpmnPropertiesPanelRenderer.js
- test/TestHelper.js
- test/spec/BpmnPropertiesPanelRenderer.spec.js
- test/util/KeyEvents.js
This follows https://github.com/bpmn-io/diagram-js/pull/662 and adds explicit handling of  undo/redo keyboard shortcuts on the properties panel to trigger diagram undo/redo.
-----
Depends on https://github.com/bpmn-io/diagram-js/pull/665 and backports (https://github.com/bpmn-io/diagram-js/pull/664, https://github.com/bpmn-io/diagram-js/pull/663)
> Explicitly bind undo/redo shortcuts to properties container

- src/provider/cloud-element-templates/create/TemplateElementFactory.js
- src/provider/cloud-element-templates/create/ZeebePropertiesProvider.js
- src/provider/cloud-element-templates/util/bindingTypes.js
- test/spec/provider/cloud-element-templates/ElementTemplates.spec.js
- test/spec/provider/cloud-element-templates/create/TemplateElementFactory.spec.js
- test/spec/provider/cloud-element-templates/create/TemplatesElementFactory.json
- `zeebe:property` bindings (cf. https://github.com/bpmn-io/bpmn-js-properties-panel/issues/731)
- optional bindings (cf. https://github.com/bpmn-io/bpmn-js-properties-panel/issues/761)
> fix: ensure `elementTemplates.createElement` supports latest features

- CHANGELOG.md
https://github.com/bpmn-io/bpmn-js-properties-panel/compare/v1.6.1...master
* `FEAT`: show conditions group if source is inclusive gateway ([#756](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/756))
* `FEAT`: support element template properties without default value ([#763](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/763))
* `FEAT`: support deprecated element templates ([#766](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/766))
* `FIX`: support `zeebe:property` binding for creation of elements from element templates ([#762](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/762))
* `FIX`: support conditional properties for creation of elements from element templates ([#762](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/762))
* `CHORE`: …
> chore(CHANGELOG): update to v1.17.0

- package-lock.json
- package.json
- test/TestHelper.js
- test/spec/BpmnPropertiesPanelRenderer.spec.js
This helps with manually testing `elementTemplates.createElement`.
> chore: add connectors extension to dev setup

- src/provider/zeebe/ZeebePropertiesProvider.js
- src/provider/zeebe/properties/TimerProps.js
- test/spec/provider/zeebe/TimerProps.bpmn
- test/spec/provider/zeebe/TimerProps.spec.js
This removes time cycle if start event is interrupting. Also, as part of a clean up, the code is simplified together with duration label (it used to be "Timer duration"):
Related to https://github.com/camunda/camunda-modeler/issues/3181
> fix(cloud): remove timeCycle for interrupting timer start event

- src/provider/camunda-platform/properties/DmnImplementationProps.js
- src/provider/camunda-platform/properties/ImplementationProps.js
- src/provider/camunda-platform/properties/ListenerProps.js
- test/spec/provider/camunda-platform/DmnImplementationProps.spec.js
- test/spec/provider/camunda-platform/ImplementationProps.spec.js
related to https://github.com/camunda/camunda-modeler/issues/3303
> fix(ImplementationProps): don't remove empty properties

- package-lock.json
- package.json
- test/TestHelper.js
- test/spec/BpmnPropertiesPanelRenderer.spec.js
This PR adds a number of quality-of-live changes to our existing test infrastructure. The purpose is to make (manual) integration testing of complex new features easier by:
* Being able to drop diagrams on the active (`npm start**`) editor instance (bc6759307d3f434d87b070ab0a61144fbe7fc253)
* Being able to download diagram in currently opened editor (to inspect its contents) (188e96c80ea42fe7e9b267890cb6751839979bef)
* Batch load all element templates into the respective playgrounds (https://github.com/bpmn-io/bpmn-js-properties-panel/commit/f05ee86164c51a57fe6d58abe547b2bedec118fb) :arrow_right: templates used during tests can be played with manually, too
(Drop file, `CTRL/CMD+S` to save).
> Test improvements

- .github/workflows/CI.yml
- CHANGELOG.md
- package.json
- src/entries/FeelEntryWithContext.js
- src/provider/HOCs/index.js
- src/provider/HOCs/withTooltipContainer.js
- src/provider/HOCs/withVariableContext.js
- src/provider/cloud-element-templates/properties/CustomProperties.js
- src/provider/zeebe/properties/AssignmentDefinitionProps.js
- src/provider/zeebe/properties/CalledDecisionProps.js
- src/provider/zeebe/properties/ConditionProps.js
- src/provider/zeebe/properties/InputOutputParameter.js
- src/provider/zeebe/properties/MessageProps.js
- src/provider/zeebe/properties/MultiInstanceProps.js
- src/provider/zeebe/properties/TargetProps.js
- src/provider/zeebe/properties/TaskDefinitionProps.js
- src/provider/zeebe/properties/TimerProps.js
- test/spec/BpmnPropertiesPanelRenderer.spec.js
- test/spec/provider/HOCs/withTooltipContainer.bpmn
- test/spec/provider/HOCs/withTooltipContainer.spec.js
- test/spec/provider/HOCs/withVariableContext.spec.js
The dev dependency update was already merged by renovate, this integrates the new features
- Restrict Tooltip placement
- Update FEEL variables on change (this breaks focus on `properties-panel<0.25`)
> Update to @bpmn-io/properties-panel@0.25.0

- src/provider/cloud-element-templates/ElementTemplatesConditionChecker.js
- test/spec/provider/cloud-element-templates/ElementTemplateConditionChecker.spec.js
- test/spec/provider/cloud-element-templates/ElementTemplates.spec.js
- test/spec/provider/cloud-element-templates/fixtures/condition-dropdown-dynamic-values-1.json
- test/spec/provider/cloud-element-templates/fixtures/condition-dropdown-dynamic-values.json
- test/spec/provider/cloud-element-templates/fixtures/condition.json
Related to https://github.com/camunda/camunda-modeler/issues/3029
There are 2 issues related to this:
* properties were being compared only by their biding to check which ones need to be added/removed -> this becomes problematic when we have properties with different conditions that share the same binding
* the template is initially applied in full and then the comparisons are made. It compared what needs to be removed but since the bindings are shared, when removing the old conditional property, the binding was removed completely.
**Artifacts to test:**
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/testing-conditional-props/camunda-modeler-testing-conditional-props-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/testing-conditional-props/ …
> Fix templates render for properties with same bindings

- CHANGELOG.md
- package-lock.json
- package.json
- src/provider/cloud-element-templates/cmd/ChangeElementTemplateHandler.js
- test/spec/provider/cloud-element-templates/ElementTemplateConditionChecker.spec.js
- test/spec/provider/cloud-element-templates/cmd/ChangeElementTemplateHandler.spec.js
- test/spec/provider/cloud-element-templates/fixtures/condition.json
- test/spec/provider/cloud-element-templates/fixtures/dropdown.json
- test/spec/provider/cloud-element-templates/fixtures/undefined-values-optional.json
- test/spec/provider/cloud-element-templates/fixtures/undefined-values.json
- test/spec/provider/cloud-element-templates/properties/CustomProperties.bpmn
- test/spec/provider/cloud-element-templates/properties/CustomProperties.json
- test/spec/provider/cloud-element-templates/properties/CustomProperties.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3327, https://github.com/camunda/camunda-modeler/issues/3327#issuecomment-1333579132
> Correct `Dropdown` rendering on undefined `zebee:input#source`

- src/provider/zeebe/properties/InputProps.js
- src/provider/zeebe/properties/OutputProps.js
- test/spec/provider/zeebe/InputProps.bpmn
- test/spec/provider/zeebe/InputProps.spec.js
- test/spec/provider/zeebe/OutputProps.bpmn
- test/spec/provider/zeebe/OutputProps.spec.js
Currently ioMappings are visually sorted.
This is a problem, because the sorting in the XML has a semantic. See https://docs.camunda.io/docs/components/concepts/variables/#inputoutput-variable-mappings: 
> Variable mappings are evaluated in the defined order. Therefore, a source expression can access the target variable of a previous mapping.
This is highly relevant in Connectors land: we need to define certain variables first, and reference them then later.
Hence I propose this as a quick fix: with this PR the sorting is at least visible in the UI. As potential follow-up, we could support a reordering via the prop panel.
related to #838
> feat: don't sort input output mappings visually

- src/provider/cloud-element-templates/UpdateTemplatePropertiesOrder.js
- src/provider/cloud-element-templates/index.js
- test/spec/provider/cloud-element-templates/fixtures/complex.bpmn
- test/spec/provider/cloud-element-templates/fixtures/update-template-properties-order.json
- test/spec/provider/cloud-element-templates/properties/UpdateTemplatePropertiesOrder.bpmn
- test/spec/provider/cloud-element-templates/properties/UpdateTemplatePropertiesOrder.json
- test/spec/provider/cloud-element-templates/properties/UpdateTemplatePropertiesOrder.spec.js
- test/spec/provider/cloud-element-templates/properties/UpdateTemplatePropertiesOrder.wrong-order.bpmn
Closes #838
We could consider refactoring `propertyUtil` later on to not delete the modified properties and just update the values instead, see https://github.com/bpmn-io/bpmn-js-properties-panel/issues/838#issuecomment-1369792405
> fix(cloud-element-templates): keep template properties order

- test/test.css
Ensure test container is full size, without hacks :tm:
The key is to make the test content container "as high as parent" using `overflow: hidden`. All content will follow suite naturally once that is settled.
> test: correct test container styles

- CHANGELOG.md
About to cut a `v1.15.0` release.
@marstamm can you review this update properly represents the latest variable improvements?
> chore(CHANGELOG): update to v1.15.0

- src/provider/shared/ExtensionPropertiesProps.js
- test/spec/provider/shared/ExtensionPropertiesProps.spec.js
Removes the check for `zeebe:PropertiesHolder` as _Extension properties_ are generally allowed.
Follow-up to https://github.com/camunda/zeebe-bpmn-moddle/pull/44
Related to https://github.com/camunda/camunda-modeler/issues/3365
> chore(zeebe): show Extension properties group for all elements

- src/provider/cloud-element-templates/properties/CustomProperties.js
- test/spec/provider/cloud-element-templates/properties/CustomProperties.spec.js
- test/spec/provider/cloud-element-templates/properties/CustomProperties.text-language.bpmn
- test/spec/provider/cloud-element-templates/properties/CustomProperties.text-language.json
Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/858
> feat: render `Text#language` fields using monospace font

- src/provider/cloud-element-templates/properties/CustomProperties.js
- test/spec/provider/cloud-element-templates/properties/CustomProperties.spec.js
This ensures that `Text` fields are auto-resizable, and assume the default content size. Such behavior is expected from multi-line text editors nowadays.
Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/858
> feat(cloud-element-templates): make `Text` fields auto-resizable

- src/provider/cloud-element-templates/UpdateTemplatePropertiesOrder.js
- test/spec/provider/cloud-element-templates/fixtures/complex.json
- test/spec/provider/cloud-element-templates/properties/UpdateTemplatePropertiesOrder.bpmn
- test/spec/provider/cloud-element-templates/properties/UpdateTemplatePropertiesOrder.json
- test/spec/provider/cloud-element-templates/properties/UpdateTemplatePropertiesOrder.spec.js
Closes #897 
Ensure inactive properties (with unmet conditions) are filtered out before re-sorting properties.
Added the Gitlab connector example with 83f30df48043f9d0115bb1179b6a296c4d6cac89. Seems like a good complex example to test but we can just use it to validate this and remove if we don't want to keep it.
> Fix element template properties order

- src/render/BpmnPropertiesPanel.js
- src/render/BpmnPropertiesPanelRenderer.js
- test/spec/BpmnPropertiesPanel.spec.js
- test/spec/BpmnPropertiesPanelRenderer.spec.js
> feat: persist layout state in localStorage

- src/provider/cloud-element-templates/properties/CustomProperties.js
- removes suggestions only for `zeebe:property` and `zeebe:taskHeader`
closes #904
> feat(cloud-templates): suggest variables for more templated properties

- src/provider/bpmn/properties/TimerProps.js
- src/provider/camunda-platform/properties/ListenerProps.js
* remove Camunda 7 concern from BPMN `TimerProps`
* import Camunda 7 `TimerProps` in Camunda 7 `ListenerProps`
Closes https://github.com/bpmn-io/bpmn-js-properties-panel/issues/910
> chore(TimerProps): separate BPMN and Camunda 7 concerns

- src/provider/bpmn/properties/SignalProps.js
- src/provider/zeebe/ZeebePropertiesProvider.js
- src/provider/zeebe/properties/SignalProps.js
- src/provider/zeebe/properties/index.js
- src/provider/zeebe/utils/InputOutputUtil.js
- test/spec/provider/zeebe/ErrorProps.spec.js
- test/spec/provider/zeebe/InputProps.bpmn
- test/spec/provider/zeebe/InputProps.spec.js
- test/spec/provider/zeebe/OutputProps.bpmn
- test/spec/provider/zeebe/OutputProps.spec.js
- test/spec/provider/zeebe/SignalProps.bpmn
- test/spec/provider/zeebe/SignalProps.spec.js
* add _Inputs_ group for signal intermediate throw and end events
* change signal _Name_ entry to optional FEEL entry
---
Closes https://github.com/bpmn-io/bpmn-js-properties-panel/issues/909
> Support Camunda 8.3 Signal Event Properties

- src/provider/cloud-element-templates/util/templateUtil.js
- src/provider/element-templates/util/templateUtil.js
- test/spec/provider/cloud-element-templates/util/templateUtil.spec.js
Related to https://github.com/bpmn-io/bpmn-js-tracking/issues/28
We already fire `elementTemplates.select`. This adds `elementTemplates.unlink`, `elementTemplates.update`, `elementTemplates.rempove`, following a similar approach to https://github.com/bpmn-io/diagram-js/issues/771.
The alternative would be relying on DOM events, which we avoided in example above.
> feat: fire template button events

- CHANGELOG.md
- src/provider/zeebe/properties/TimerProps.js
- src/provider/zeebe/utils/TimerUtil.js
- test/spec/provider/zeebe/TimerProps.bpmn
- test/spec/provider/zeebe/TimerProps.spec.js
- test/spec/utils/TimerUtil.bpmn
- test/spec/utils/TimerUtilSpec.js
* adds support for time duration for timer start events in event sub-processes (supported by Zeebe)
* adds support for time date for timer intermediate catch and boundary events (supported by Zeebe 8.3)
* removes handling cases of only one timer expression type available (and removes legacy IDs)
* refactors tests
---
Depends on https://github.com/camunda/camunda-bpmn-js-behaviors/pull/36
Related to https://github.com/camunda/camunda-modeler/issues/3516
> feat: allow time date in boundary and intermediate catch events

- CHANGELOG.md
- src/provider/cloud-element-templates/ElementTemplatesConditionChecker.js
- src/provider/cloud-element-templates/ReferencedElementBehavior.js
- src/provider/cloud-element-templates/util/rootElementUtil.js
- test/spec/provider/cloud-element-templates/ElementTemplateConditionChecker.spec.js
- test/spec/provider/cloud-element-templates/fixtures/condition-message.bpmn
- test/spec/provider/cloud-element-templates/fixtures/condition-message.json
If a conditional template deactivates all of the `bpmn:Message` bindings, the message is removed altogether. This feature will be important especially for templating catch-all events, i.e. error and escalation.
Closes #915
> feat: remove templated message if no message bindings are active

- CHANGELOG.md
- package-lock.json
- package.json
> Update properties panel peer dependency

- src/provider/zeebe/utils/InputOutputUtil.js
- test/spec/provider/zeebe/ZeebePropertiesProvider.bpmn
- test/spec/provider/zeebe/ZeebePropertiesProvider.spec.js
related to https://github.com/camunda/camunda-modeler/issues/3782
Removal of output mappings already present is a follow-up action and is done in https://github.com/camunda/camunda-bpmn-js-behaviors/tree/master/test/camunda-cloud
> fix(zeebe): remove output group from error end events

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- rollup.config.mjs
- test/distro/distroSpec.js
This helps us streamline our release process and prevents css mismatches in downstream libraries.
Related Slack discussion: https://camunda.slack.com/archives/GP70M0J6M/p1692870672157409
> Remove properties panel css

- src/provider/zeebe/ZeebePropertiesProvider.js
- src/provider/zeebe/properties/InputPropagationProps.js
- src/provider/zeebe/properties/index.js
- src/provider/zeebe/utils/CalledElementUtil.js
- test/spec/provider/zeebe/InputPropagationProps.bpmn
- test/spec/provider/zeebe/InputPropagationProps.spec.js
- test/spec/provider/zeebe/OutputPropagationProps.spec.js
Adds a option to configure the
`CalledElement#propagateAllParentVariables` when modeling a Call Activity.
closes #953
> feat: add support for `CalledElement#propagateAllParentVariables`

- CHANGELOG.md
- package-lock.json
- package.json
- src/render/index.js
- test/spec/BpmnPropertiesPanelRenderer.spec.js
Closes #974
Adds the core `feelPopup` module to interact with the FEEL popup editor in a non-UI manner.
> feat(feel-popup): include feel popup module

- src/provider/zeebe/properties/InputProps.js
- src/provider/zeebe/properties/OutputProps.js
- test/spec/provider/zeebe/InputOutputParameter.spec.js
This PR removes the empty `source` value for newly created Input/Output parameters. I decided to go with the convention "no value => remove property" that we use in other places, such as Task definition type. I verified that the deployment error in zeebe is the same for empty value and missing property.
I added integration tests to verify the scenario described in #981.
> fix(Input/Output): keep undo/redo stack

- src/provider/HOCs/withVariableContext.js
- test/spec/BpmnPropertiesPanelRenderer.spec.js
- test/spec/provider/HOCs/withVariableContext.bpmn
- test/spec/provider/HOCs/withVariableContext.spec.js
We added this functionality to the variable resolver a while back but never properly integrated it. Ooops. Better late than never I guess. 
related to https://github.com/camunda/camunda-modeler/issues/3510
> feat(FEEL): use moddle element to filter for variables 

- .github/workflows/CI.yml
This aims to allow us to discover quickly whether a CI failure is caused by incompatibility or another problem.
> ci: continue if peer deps job fails

- CHANGELOG.md
- package-lock.json
- package.json
- src/provider/zeebe/properties/MessageProps.js
- test/spec/provider/zeebe/MessageProps.spec.js
Let's cut this release to integrate the changes downstream!
> Prepare v5.6.0

- src/contextProvider/zeebe/TooltipProvider.js
The docs themselves still need to be updated to reflect form linking.
> chore: adjust `Forms` group tooltip

- src/provider/camunda-platform/properties/FormProps.js
- src/provider/zeebe/properties/FormProps.js
- test/spec/provider/camunda-platform/FormProps.spec.js
- test/spec/provider/zeebe/Forms.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/3963
> fix: do not unset form type when setting value to empty

- src/provider/bpmn/properties/IdProps.js
- src/provider/bpmn/properties/ProcessProps.js
- test/spec/provider/bpmn/IdProps.spec.js
- test/spec/provider/bpmn/ProcessProps.spec.js
Root cause: not properly using Callback hooks, changing the Validation function every render. This caused a recheck with the correct value, since the incorrect one is not applied to the XML.
> fix(Id): create validation function as callback

- src/contextProvider/zeebe/TooltipProvider.js
- src/provider/zeebe/properties/TaskDefinitionProps.js
Improves the retries tooltip to more closely resemble reality (total number of times an activity is attempted to be executed, rather than 1 + retriesCount.
Documentation ("Learn more") links to [this page](https://docs.camunda.io/docs/next/components/best-practices/development/dealing-with-problems-and-exceptions/#leveraging-retries).
----
Related to https://github.com/camunda/camunda-modeler/issues/4148
> fix(zeebe): correct retries tooltip

- CHANGELOG.md
- package-lock.json
- package.json
- src/provider/camunda-platform/properties/ErrorsProps.js
- src/provider/camunda-platform/properties/FormDataProps.js
- src/provider/camunda-platform/properties/FormField.js
- src/provider/camunda-platform/properties/InputProps.js
- src/provider/camunda-platform/properties/ListProps.js
- src/provider/camunda-platform/properties/ListenerProps.js
- src/provider/camunda-platform/properties/MapProps.js
- src/provider/camunda-platform/properties/OutputProps.js
- src/provider/camunda-platform/properties/ProcessVariablesProps.js
- src/provider/shared/ExtensionPropertiesProps.js
- src/provider/zeebe/properties/BusinessRuleImplementationProps.js
- src/provider/zeebe/properties/HeaderProps.js
- src/provider/zeebe/properties/InputProps.js
- src/provider/zeebe/properties/OutputProps.js
- test/spec/provider/camunda-platform/FormField.spec.js
- test/spec/provider/camunda-platform/FormFieldProperty.spec.js
- test/spec/provider/zeebe/BusinessRuleImplementationProps.spec.js
- test/spec/provider/zeebe/ScriptImplementationProps.spec.js
- test/spec/provider/zeebe/UserTaskImplementationProps.spec.js
This pull request aims to fix [#311 in properties-panel](https://github.com/bpmn-io/properties-panel/issues/311) together [#353 in properties-panel](https://github.com/bpmn-io/properties-panel/pull/353). Currently, it is being developed.
=> Potentially every component which did not explicitly set `shouldSort` to `false`, but we should use  this opportunity to evaluate where it actually should be sorted.
Regarding the `shouldSort` flag, I saw the following throughout this project.
**Camunda 7 - Camunda Platform**
Usages without the `shouldSort` flags, thus using the previous default of sorting:
- FieldInjectionGroup
- InMappingGroup
- OutMappingGroup
- ExecutionListenerGroup
- TaskListenerGroup
- ConnectorInputGroup
- ConnectorOutputGroup
- ExtensionPropertiesGroup
Usages with the …
> Remove unsupported flag "shouldSort"

- package-lock.json
- package.json
- src/provider/camunda-platform/properties/FieldInjection.js
- src/provider/zeebe/properties/Header.js
- test/spec/provider/camunda-platform/FieldInjectionProps.spec.js
- test/spec/provider/zeebe/Header.spec.js
As a user I want to be able to conveniently put multiple lines of text into Header value input and Field Injection value input.
Updated dependency to `@bpmn-io/properties-panel` as the new version has a fix for UX of text area. Don't want to introduce new text areas that I know would be bugged.
Related to https://github.com/camunda/camunda-modeler/issues/2982
> feat: change Header value input and Field Injection value input to text areas

- package-lock.json
- package.json
- src/provider/zeebe/ZeebePropertiesProvider.js
- src/provider/zeebe/properties/ExecutionListener.js
- src/provider/zeebe/properties/ExecutionListenersProps.js
- src/provider/zeebe/properties/index.js
- test/spec/provider/zeebe/ExecutionListenerProps.bpmn
- test/spec/provider/zeebe/ExecutionListenerProps.spec.js
https://github.com/user-attachments/assets/7f18da21-bb77-4418-bec1-14b3bbf47892
Related to https://github.com/camunda/camunda-modeler/issues/3951
Try out via `npm start` on the branch.
> feat: add execution listeners for Zeebe

- package-lock.json
- package.json
- src/contextProvider/zeebe/TooltipProvider.js
- src/provider/HOCs/index.js
- src/provider/HOCs/withProps.js
- src/provider/zeebe/properties/CalledDecisionProps.js
- src/provider/zeebe/properties/FormProps.js
- src/provider/zeebe/properties/TargetProps.js
- src/provider/zeebe/properties/shared/Binding.js
- src/provider/zeebe/utils/CalledElementUtil.js
- test/spec/provider/zeebe/CalledDecisionProps.spec.js
- test/spec/provider/zeebe/Forms.spec.js
- test/spec/provider/zeebe/TargetProps.spec.js
* adds a _Binding_ entry to business rule tasks implemented as DMN, call activities and user tasks with linked form 
Check out the branch and run `npm start` to test.
Depends on https://github.com/camunda/camunda-bpmn-js-behaviors/pull/78
Depends on https://github.com/bpmn-io/properties-panel/pull/376
---
Related to https://github.com/camunda/camunda-modeler/issues/4385
> Add _Binding_ entry to busines rule task, call activity and user task

- package-lock.json
- package.json
- src/contextProvider/zeebe/TooltipProvider.js
- src/provider/zeebe/ZeebePropertiesProvider.js
- src/provider/zeebe/properties/PriorityDefinitionProps.js
- src/provider/zeebe/properties/index.js
- test/spec/provider/zeebe/PriorityDefinitionProps.bpmn
- test/spec/provider/zeebe/PriorityDefinitionProps.spec.js
Adds an entry in the properties panel to edit the `zeebe:priorityDefinition::priority` of a user task. Should have a tooltip with some info and a (currently empty) link to docs. 
Closes #1069
`npx @bpmn-io/sr bpmn-io/bpmn-js#main -l bpmn-io/bpmn-js-properties-panel#1069-support-priority-editing`
> feat: support editing `zeebe:priorityDefinition`

- package-lock.json
- package.json
- src/contextProvider/zeebe/TooltipProvider.js
- src/provider/zeebe/ZeebePropertiesProvider.js
- src/provider/zeebe/properties/CalledDecisionProps.js
- src/provider/zeebe/properties/FormProps.js
- src/provider/zeebe/properties/TargetProps.js
- src/provider/zeebe/properties/VersionTagProps.js
- src/provider/zeebe/properties/index.js
- src/provider/zeebe/properties/shared/VersionTag.js
- test/spec/provider/zeebe/CalledDecisionProps.bpmn
- test/spec/provider/zeebe/CalledDecisionProps.spec.js
- test/spec/provider/zeebe/Forms.bpmn
- test/spec/provider/zeebe/Forms.spec.js
- test/spec/provider/zeebe/TargetProps.bpmn
- test/spec/provider/zeebe/TargetProps.spec.js
- test/spec/provider/zeebe/VersionTagProps-collaboration.bpmn
- test/spec/provider/zeebe/VersionTagProps-process.bpmn
- test/spec/provider/zeebe/VersionTagProps.spec.js
* adds _Version tag_ field to processes
* adds _Version tag_ field to resources linked through _version tag_ option
* adjusts the _Binding type_ tooltip
Requires https://github.com/camunda/zeebe-bpmn-moddle/pull/65
Requires https://github.com/camunda/camunda-bpmn-js-behaviors/pull/80
> Add `Version tag` field

- src/provider/zeebe/properties/CalledDecisionProps.js
- src/provider/zeebe/properties/FormProps.js
- src/provider/zeebe/properties/TargetProps.js
Creates the component only once so that React doesn't replace it in the DOM on every render assuming it's a different component.
---
Related to https://github.com/camunda/camunda-modeler/issues/4513
> Don't create new `Binding` and `Version tag` components on every render

- src/provider/zeebe/properties/PriorityDefinitionProps.js
- test/spec/provider/zeebe/PriorityDefinitionProps.bpmn
- test/spec/provider/zeebe/PriorityDefinitionProps.spec.js
Related to [#21772](https://github.com/camunda/camunda/issues/21772)
> fix: only show priority  assignment in `zeebe:userTask`

- CHANGELOG.md
- package-lock.json
- package.json
- src/render/BpmnPropertiesPanel.js
- src/render/BpmnPropertiesPanelRenderer.js
- test/spec/BpmnPropertiesPanelRenderer.spec.js
* makes the links shown in the FEEL popup editor configurable
* links can be configured by end user instead of being hard-coded in core properties panel
Depends on https://github.com/bpmn-io/properties-panel/pull/382
Related to https://github.com/camunda/product-hub/issues/2070#issuecomment-2449888911
> Make FEEL Popup Links Configurable

- src/render/BpmnPropertiesPanel.js
- src/render/BpmnPropertiesPanelRenderer.js
- test/spec/BpmnPropertiesPanelRenderer.spec.js
We don't need it since we require more
recent diagram-js version.
This removes the ID check for implicit root which was required prior to diagram-js@7.4.0
> chore: remove legacy check

- test/spec/BpmnPropertiesPanelRenderer.spec.js
The `keyboard.bindTo` was deprecated and shouldn't be used anymore so this PR removes the leftover from one of the tests still using it
This issue was pointed in the [comment](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1087#issuecomment-2462681373)
> test: remove deprecated `keyboard.bindTo`

- CHANGELOG.md
- package-lock.json
- package.json
- src/provider/zeebe/ZeebePropertiesProvider.js
- src/provider/zeebe/properties/TaskListener.js
- src/provider/zeebe/properties/TaskListenersProps.js
- src/provider/zeebe/properties/index.js
- src/provider/zeebe/properties/shared/Listener.js
- test/spec/provider/zeebe/TaskListenerProps.bpmn
- test/spec/provider/zeebe/TaskListenerProps.spec.js
related to https://github.com/camunda/camunda-modeler/issues/4590
Add task listener to user task.
[Screencast from 2024-11-07 13-56-29.webm](https://github.com/user-attachments/assets/58f725fd-d34d-4e1e-9e61-cb6805456368)
can be tested with `npm start` on the branch
> feat: add task listeners for Zeebe

- src/render/BpmnPropertiesPanelRenderer.js
Related to https://github.com/bpmn-io/internal-docs/issues/1081
By making properties panel container focusable, user can click somewhere in the container (not only on buttons and inputs) to continue using keyboard shortcuts in the context of the panel.
> feat: make properties panel container focusable

- README.md
Remove a long obsolete notice.
> docs: remove `0.x` notice, we are the future now

- package-lock.json
- package.json
- src/provider/zeebe/properties/TaskListener.js
- src/provider/zeebe/properties/TaskListenersProps.js
- test/spec/provider/zeebe/TaskListenerProps.bpmn
- test/spec/provider/zeebe/TaskListenerProps.spec.js
https://github.com/user-attachments/assets/df186973-11e8-4a8c-a3d7-3198ed9931ad
This implements the event types change. The legacy name is displayed in a label and can be changed in a one-way manner.
We could consider displaying the unknown name in the select too, but this means it will still appear in the options to select.
Related to https://github.com/camunda/camunda-modeler/issues/4748
Requires https://github.com/camunda/camunda-bpmn-js-behaviors/pull/92 to be released and integrated.
> feat: rename task listener event types

- .github/workflows/CI.yml
- CHANGELOG.md
- src/provider/zeebe/properties/TaskListener.js
- test/spec/provider/zeebe/TaskListenerProps.spec.js
This PR ensures that event types are displayed in logical order (first assigning, then completing):
Related to https://camunda.slack.com/archives/C0622NWC9LK/p1736529715729349?thread_ts=1736529030.781279&cid=C0622NWC9LK
> fix: ensure logical order of task listener event types

- package-lock.json
- package.json
- src/contextProvider/zeebe/TooltipProvider.js
- src/provider/zeebe/ZeebePropertiesProvider.js
- src/provider/zeebe/properties/ActiveElementsProps.js
- src/provider/zeebe/properties/index.js
- test/spec/provider/zeebe/ActiveElementsCollectionProps.bpmn
- test/spec/provider/zeebe/ActiveElementsCollectionProps.spec.js
Add Active elements group with Active elements collection FEEL field for ad-hoc subprocess.
Related to https://github.com/camunda/camunda-modeler/issues/4739
> feat: support ad-hoc subprocesses

- src/provider/zeebe/properties/ActiveElementsProps.js
Fix import paths
Closes https://github.com/bpmn-io/bpmn-js-properties-panel/issues/1106
> chore: fix import paths

- src/contextProvider/zeebe/TooltipProvider.js
- test/spec/provider/zeebe/MessageProps.spec.js
Related to camunda-modeler: [#4833](https://github.com/camunda/camunda-modeler/issues/4833)
Added tooltip for Subscription correlation key
> fix: subscription coorelation key tooltip added

- test/spec/provider/bpmn/EscalationProps.spec.js
- test/spec/provider/bpmn/SignalProps.spec.js
- test/spec/provider/zeebe/BusinessRuleImplementationProps.spec.js
- test/spec/provider/zeebe/ConditionProps.spec.js
- test/spec/provider/zeebe/ScriptImplementationProps.spec.js
- test/spec/provider/zeebe/UserTaskImplementationProps.spec.js
This fixes some tests which used to throw uncaught promise exceptions.
I propose also to stop testing for the edited dot existence. These assertions are super flaky and slow (`wait 50 ms` included), and a rewrite to `waitFor` did not resolve flakiness on my machine. I don't think this is a crucial feature, and we tested for it only in some places in the code base.
> Fix broken tests

- CHANGELOG.md
- package-lock.json
- package.json
Related to : camunda-modeler [#4818](https://github.com/camunda/camunda-modeler/issues/4818)
- deps update
- fixes upstream issue: https://github.com/bpmn-io/properties-panel/pull/402
> deps: update/properties panel@3.26.3

- src/contextProvider/zeebe/TooltipProvider.js
- src/provider/bpmn/BpmnPropertiesProvider.js
- src/provider/bpmn/properties/AdHocCompletionProps.js
- src/provider/bpmn/properties/MultiInstanceProps.js
- src/provider/bpmn/properties/index.js
- src/provider/zeebe/ZeebePropertiesProvider.js
- src/provider/zeebe/properties/AdHocCompletionProps.js
- src/provider/zeebe/properties/MultiInstanceProps.js
- src/provider/zeebe/properties/index.js
- src/utils/FormalExpressionUtil.js
- test/spec/provider/bpmn/AdHocCompletionProps.bpmn
- test/spec/provider/bpmn/AdHocCompletionProps.spec.js
- test/spec/provider/zeebe/AdHocCompletionProps.bpmn
- test/spec/provider/zeebe/AdHocCompletionProps.spec.js
Adds support to configure `completionCondition` (expression) and `cancelRemainingInstances` (boolean) for ad-hoc subprocesses.
**BPMN implementation**
**Zeebe specific implementation**
Related to https://github.com/camunda/camunda-modeler/issues/4850.
> feat: add completionCondition + cancelRemainingInstances properties to ad-hoc subprocess

- src/contextProvider/zeebe/TooltipProvider.js
Related to https://github.com/camunda/camunda-modeler/issues/4889
Adjust wording for input/output groups as proposed by @nikku in https://github.com/camunda/camunda-modeler/issues/4889#issuecomment-2711239895
> Adjust wording for inpout/output groups

- CHANGELOG.md
- package-lock.json
- package.json
* `DEPS`: update to `@bpmn-io/properties-panel@3.26.4`
* `FIX`: reverts trim trailing whitespaces from all input fields except expressions ([bpmn-io/properties-panel#309](https://github.com/bpmn-io/properties-panel/issues/309)) added in `5.33.0`
> Bump dep properties-panel

- src/contextProvider/zeebe/TooltipProvider.js
Update the tooltip for the [recently introduced ad-hoc completion](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1114) to jump to the completion section which was added in https://github.com/camunda/camunda-docs/pull/5235.
Related to https://github.com/camunda/camunda-modeler/issues/4850
> Update tooltip to ad-hoc completion to jump to the completion section

- CHANGELOG.md
- package-lock.json
- package.json
- src/provider/camunda-platform/properties/ConditionProps.js
- test/fixtures/integration.bpmn
- test/spec/BpmnPropertiesPanelRenderer.spec.js
> [!NOTE]
>   The issue was found in `@bpmn-io/properties-panel v3.26.3`
Related to: https://github.com/bpmn-io/properties-panel/issues/404
Discussion: https://github.com/bpmn-io/properties-panel/issues/404#issuecomment-2724827682, https://camunda.slack.com/archives/GP70M0J6M/p1742391873712439
Upstream PR: https://github.com/bpmn-io/properties-panel/pull/405 (merged and released)
- Issue was resolved but was not able to reproduce the test case where input propogate from one element to other in properties-panel ([ref.](https://github.com/camunda/web-modeler/issues/13599) )
- Added a fix where element was not provided as props to the textfield, since the input callback now depends on element after https://github.com/bpmn-io/properties-panel/pull/416#issuecomment-2911632188
Following …
> Integration tests for trimmed inputs

- src/provider/zeebe/properties/UserTaskImplementationProps.js
- test/spec/provider/zeebe/UserTaskImplementationProps.spec.js
Closes #1135
Inverses the implementation type for which the isEdited dot shows in user tasks. 
Above is the before state. I tested via yalc in web modeler and the fix worked, although I forgot to take a screenshot.
To test, yalc publish this branch, yalc add in desktop or web modeler, then add a user task.
> fix: flip user task implementation type isEdited default
