bpmn-io/bpmn-js-properties-panel

lib/provider/camunda/camunda-moddle.json

Use correct camunda namespace

---

styles/properties.less

Set width with respect to parent padding

---

lib/provider/camunda/parts/VariableMappingProps.js
test/spec/provider/camunda/SignalEventVariableMappingSpec.js

See Camunda Modeler issue: https://github.com/camunda/camunda-modeler/issues/818

Remove target attribute from variable mapping when type changed to 'all'

---

.travis.yml

This should fix the current CI timeout-errors

chore(ci): run test on node_js@10

---

package-lock.json
package.json

chore(project): bump dependencies

---

lib/provider/camunda/CamundaPropertiesProvider.js
lib/provider/camunda/parts/TasklistProps.js
lib/provider/camunda/parts/implementation/Tasklist.js
package-lock.json
package.json
test/spec/provider/camunda/TasklistParticipant.bpmn
test/spec/provider/camunda/TasklistProcess.bpmn
test/spec/provider/camunda/TasklistSpec.js

Related to camunda/camunda-modeler#843

feat(properties): edit isStartableInTasklist

---

CHANGELOG.md
lib/provider/camunda/parts/implementation/Tasklist.js
package-lock.json
package.json
test/spec/provider/camunda/TasklistParticipant.bpmn
test/spec/provider/camunda/TasklistProcess.bpmn
test/spec/provider/camunda/TasklistSpec.js

Correctly handles `camunda:isStartableInTasklist` default parameter

Default attr task stuff

---

lib/PropertiesPanel.js

* Fix a typo in the documentation Booelan -> Boolean
* Add a final eol

chore(PropertiesPanel): fix typo in documentation

---

styles/properties.less

Related to camunda/camunda-modeler#1034

fix(styles): remove accidental whitespace

---

lib/factory/EntryFieldDescription.js
test/spec/factory/EntryFieldDescriptionSpec.js

Handle line breaks in EntryFieldDescriptions

---

lib/Utils.js
test/spec/UtilsSpec.js
test/spec/provider/bpmn/IdSpec.js

Fixes: https://github.com/camunda/camunda-modeler/issues/1623
Will do the same for dmn-js-properties-panel/cmmn-js-properties-panel

Deprecate placeholders

---

lib/PropertiesPanel.js
test/TestHelper.js
test/spec/PropertiesPanelSpec.js
test/spec/properties/PropertiesProvider.js

265 paste text only to content editable divs

---

lib/provider/camunda/parts/FormProps.js

* Add a hint in the UI that the ID of a Form Field becomes the name of a process variable.

feat(form-fields): add hint that ID defines variable name

---

lib/factory/SelectEntryFactory.js

* This is a small extra feature allowing to provide a [title attribute](https://www.w3schools.com/tags/att_title.asp) for adding tooltips to dropdown menu options

Support (optional) tooltip for drop down options

---

CHANGELOG.md
package.json

chore(CHANGELOG): update to v0.34.0

---

styles/_mixins.less
styles/_variables.less
styles/groups.less
styles/header.less
styles/listeners.less
styles/properties.less
styles/tabs.less

Implement new colors

---

lib/provider/camunda/CamundaPropertiesProvider.js
lib/provider/camunda/parts/ProcessVariablesProps.js
lib/provider/camunda/parts/implementation/ProcessVariables.js
package-lock.json
package.json
styles/properties.less
test/spec/provider/camunda/ProcessVariables-collaboration.bpmn
test/spec/provider/camunda/ProcessVariables.bpmn
test/spec/provider/camunda/ProcessVariablesSpec.js

Closes #343 
Available for following elements
* `bpmn:Process`
* `bpmn:Participant`
* `bpmn:SubProcess`

Variables Overview

---

lib/PropertiesPanel.js
lib/factory/CheckboxEntryFactory.js
lib/factory/CollapsibleEntryFactory.js
lib/factory/ComboEntryFactory.js
lib/factory/EntryFactory.js
lib/factory/EntryFieldDescription.js
lib/factory/LinkEntryFactory.js
lib/factory/SelectEntryFactory.js
lib/factory/TableEntryFactory.js
lib/factory/TextBoxEntryFactory.js
lib/factory/TextInputEntryFactory.js
styles/_variables.less
styles/properties.less
test/spec/PropertiesPanelSpec.js
test/spec/factory/CollapsibleEntryFactorySpec.js
test/spec/factory/EntryFieldDescriptionSpec.js

Implement details component

---

lib/provider/camunda/CamundaPropertiesProvider.js
lib/provider/camunda/parts/ProcessVariablesProps.js
lib/provider/camunda/parts/implementation/ProcessVariables.js
styles/properties.less
test/spec/provider/camunda/ProcessVariables-collaboration.bpmn
test/spec/provider/camunda/ProcessVariables-no-variables.bpmn
test/spec/provider/camunda/ProcessVariablesSpec.js

feat(camunda): improve process variables overview

---

lib/PropertiesPanel.js
lib/provider/camunda/CamundaPropertiesProvider.js
lib/provider/camunda/element-templates/CustomElementsPropertiesActivator.js
lib/provider/camunda/element-templates/parts/DescriptionProps.js
styles/_variables.less
styles/groups.less
styles/properties.less
test/spec/provider/camunda/element-templates/parts/DescriptionProps.bpmn
test/spec/provider/camunda/element-templates/parts/DescriptionPropsSpec.js

Related to camunda/camunda-modeler#1891

feat(element-template-tab): indicate element template not found

---

lib/provider/camunda/CamundaPropertiesProvider.js
lib/provider/camunda/element-templates/Validator.js
lib/provider/camunda/element-templates/parts/CustomProps.js
lib/provider/camunda/element-templates/parts/InputParametersProps.js
lib/provider/camunda/element-templates/parts/OutputParametersProps.js
styles/properties.less
test/spec/provider/camunda/element-templates/ValidatorSpec.js
test/spec/provider/camunda/element-templates/fixtures/missing-types.json
test/spec/provider/camunda/element-templates/parts/CustomProps.missing-types.bpmn
test/spec/provider/camunda/element-templates/parts/CustomProps.missing-types.json
test/spec/provider/camunda/element-templates/parts/CustomPropsSpec.js
test/spec/provider/camunda/element-templates/parts/InputParametersProps.bpmn
test/spec/provider/camunda/element-templates/parts/InputParametersProps.json
test/spec/provider/camunda/element-templates/parts/InputParametersPropsSpec.js
test/spec/provider/camunda/element-templates/parts/OutputParametersProps.bpmn
test/spec/provider/camunda/element-templates/parts/OutputParametersProps.json
test/spec/provider/camunda/element-templates/parts/OutputParametersPropsSpec.js

Closes #358 
--------------------------
Depends on Changes of #360 
Depends on Changes of #364 
Depends on Changes of #367

Template Input Output Groups

---

lib/provider/camunda/parts/implementation/ProcessVariables.js

chore(camunda): update variables overview description

---

CHANGELOG.md
package-lock.json
package.json

Update Changelog + Bump diagram-js

---

lib/provider/camunda/element-templates/parts/InputParametersProps.js
lib/provider/camunda/element-templates/parts/OutputParametersProps.js
test/spec/provider/camunda/element-templates/parts/InputParametersPropsSpec.js
test/spec/provider/camunda/element-templates/parts/OutputParametersPropsSpec.js

fix(element-templates): always use current parameter

---

styles/groups.less
styles/properties.less
test/spec/PropertiesPanelSpec.js

Closes #359
Also added testcases for relevant html validation rendering

fix(properties-panel): render validation error below checkbox labes

---

lib/provider/camunda/element-templates/CustomElementsPropertiesActivator.js
test/spec/provider/camunda/element-templates/parts/VisibilitySpec.js

Related to camunda/camunda-modeler#1975

fix(element-templates): re-enable `entriesVisible`

---

lib/provider/camunda/element-templates/ReplaceBehavior.js
lib/provider/camunda/element-templates/index.js
test/spec/provider/camunda/element-templates/ReplaceBehaviorSpec.js
test/spec/provider/camunda/element-templates/fixtures/replace-behavior.bpmn
test/spec/provider/camunda/element-templates/fixtures/replace-behavior.json

Related to https://github.com/camunda/camunda-modeler/issues/1961

fix(element-template): unlink template on replace

---

CHANGELOG.md
lib/provider/camunda/parts/implementation/Script.js
test/spec/provider/camunda/Connector.bpmn
test/spec/provider/camunda/ConnectorSpec.js
test/spec/provider/camunda/InputOutput.bpmn
test/spec/provider/camunda/InputOutputParameterTextSpec.js
test/spec/provider/camunda/InputParametersSpec.js

Closes [camunda/camunda-modeler#2007](https://github.com/camunda/camunda-modeler/issues/2007) (fix-upstream)

2007 inside connector script fix

---

CHANGELOG.md

chore(CHANGELOG): update to v0.38.0

---

lib/provider/camunda/element-templates/parts/DescriptionProps.js
lib/provider/camunda/element-templates/parts/Helper.js
test/spec/provider/camunda/element-templates/parts/DescriptionPropsSpec.js

Related to camunda/camunda-modeler#2053

fix(templates): fix displayed version in description

---

package-lock.json
package.json

chore: bump to bpmn-js@8

---

lib/provider/bpmn/BpmnPropertiesProvider.js
lib/provider/bpmn/parts/IdProps.js
lib/provider/bpmn/parts/NameProps.js
lib/provider/camunda/CamundaPropertiesProvider.js
test/spec/provider/bpmn/ProcessParticipantCollapsedSpec.js
test/spec/provider/bpmn/ProcessParticipantExpandedSpec.js
test/spec/provider/bpmn/ProcessParticipantSpec.js

Add 'participant-' prefix to name and id inputs for clarity

---

docs/RELEASE_CHECKLIST.md

n/a.
Update need was discovered as we are releasing the repo.

chore(RELEASE): update release checklist

---

package-lock.json
package.json

Adds extraction of event definition variables.

chore: bump @bpmn-io/extract-process-variables

---

CHANGELOG.md
package-lock.json
package.json

Locally tested using https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel => works
Related to https://github.com/camunda/camunda-modeler/issues/2077

Prepare release

---

lib/provider/camunda/element-templates/Validator.js
package-lock.json
package.json
test/spec/provider/camunda/element-templates/ValidatorSpec.js
test/spec/provider/camunda/element-templates/fixtures/simple-high-schema-version.json
test/spec/provider/camunda/element-templates/fixtures/simple-latest-schema-version.json
test/spec/provider/camunda/element-templates/fixtures/simple-low-schema-version.json
test/spec/provider/camunda/element-templates/fixtures/simple-mixed-schema-version.json
test/spec/provider/camunda/element-templates/fixtures/simple-same-schema-version.json

related to camunda/camunda-modeler#2083
Follow-ups:
* (Maybe) make errors easier to interpret (e.g., "ignoring template"?)
* Do the actual template valation using the schema

feat: ignore non-supported element template schema versions

---

lib/provider/camunda/element-templates/parts/DescriptionProps.js
test/spec/provider/camunda/element-templates/parts/DescriptionPropsSpec.js

fixes upstream camunda/camunda-modeler#2101

fix(element-templates): don't render version label given no version

---

package-lock.json

This PR updates the lockfileVersion to align with stable versions of npm

Update lockfileVersion to 1

---

styles/properties.less

https://user-images.githubusercontent.com/28307541/112017124-9e445680-8b2d-11eb-865d-b640e3ee04e1.mp4
Related to https://github.com/camunda/camunda-modeler/issues/2166

fix(collapsible): display necessary part of title

---

package-lock.json
package.json
test/spec/provider/camunda/ScriptProperties.bpmn

Related to https://github.com/bpmn-io/bpmn-js-properties-panel/pull/467

Bump bpmn js 8.3.1

---

lib/provider/camunda/element-templates/CreateHelper.js
test/spec/provider/camunda/element-templates/CreateHelperSpec.js

* This follows an hour-of-code discussion where we identified that the
affected lines of code are hard to understand and maintain without
the now added documentation

chore(elementTemplates): refactor createHelper for camunda:in|out

---

lib/PropertiesPanel.js
package-lock.json
package.json
test/spec/PropertiesPanelSpec.js

* adjust to changes in implicit root ID

deps: update diagram-js to 7.4.0

---

src/provider/camunda-platform/properties/ImplementationProps.js
src/provider/camunda-platform/properties/ImplementationTypeProps.js
test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider-Process.bpmn
test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider.spec.js
test/spec/provider/camunda-platform/ImplementationProps.bpmn
test/spec/provider/camunda-platform/ImplementationTypeProps.spec.js

508 missing impelementation type

---

src/provider/camunda-platform/properties/ImplementationProps.js

chore(implementationProps): change let to const

---

src/provider/camunda-platform/properties/ConditionProps.js
test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider-Process.bpmn
test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider.spec.js
test/spec/provider/camunda-platform/ConditionProps.bpmn
test/spec/provider/camunda-platform/ConditionProps.spec.js

507 inclusive gateway condition

---

package-lock.json
package.json
src/contextProvider/zeebe/DescriptionProvider.js
src/contextProvider/zeebe/index.js
src/provider/zeebe/properties/ConditionProps.js
src/provider/zeebe/properties/MessageProps.js
src/provider/zeebe/properties/TargetProps.js
src/provider/zeebe/properties/TaskDefinitionProps.js
src/render/BpmnPropertiesPanel.js
src/render/BpmnPropertiesPanelRenderer.js
test/spec/BpmnPropertiesPanel.spec.js
test/spec/BpmnPropertiesPanelRenderer.spec.js
test/spec/provider/zeebe/MessageProps.bpmn
test/spec/provider/zeebe/MessageProps.spec.js
test/spec/provider/zeebe/TaskDefinitionProps.spec.js

requires bpmn-io/properties-panel#122
closes bpmn-io/properties-panel#119

Add description context

---

src/contextProvider/zeebe/DescriptionProvider.js

Requested via https://docs.google.com/document/d/1Wc87TbWwTehDdpfMLlyK4ANHVeZZAsReiFPDxysf-AI/edit#
cc @felix-mueller

feat(descriptionProvider): add link for error events

---

README.md

chore: link 0.x branch in the readme

---

src/provider/zeebe/properties/MultiInstanceProps.js
test/spec/provider/zeebe/MultiInstanceProps.bpmn
test/spec/provider/zeebe/MultiInstanceProps.spec.js

Support completion condition for multi-instance

---

src/provider/zeebe/ZeebePropertiesProvider.js
src/provider/zeebe/utils/ZeebeServiceTaskUtil.js
test/spec/provider/zeebe/BusinessRuleImplementationProps.spec.js
test/spec/provider/zeebe/CalledDecisionProps.spec.js
test/spec/provider/zeebe/TaskDefinitionProps.spec.js
test/spec/provider/zeebe/ZeebePropertiesProvider.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/2524

feat: re-enable zeebe:calledDecision

---

package-lock.json
package.json

deps: bumping properties-panel dep to 0.10.1

---

assets/element-templates.css
src/provider/element-templates/components/ElementTemplatesGroup.js

fix(elementTemplates): reorder unlink / remove actions in dropdown

---

src/index.js

related to camunda/camunda-bpmn-js#83

chore: export DescriptionProvider as ZeebeDescriptionProvider

---

package-lock.json
package.json
src/provider/camunda-platform/properties/ProcessVariablesProps.js
src/render/PanelHeaderProvider.js
test/TestHelper.js
test/spec/BpmnPropertiesPanelRenderer.spec.js
test/spec/PanelHeaderProvider.spec.js
test/spec/provider/camunda-platform/ProcessVariablesProps-process.bpmn
test/spec/provider/camunda-platform/ProcessVariablesProps.spec.js

This PR ensures that the properties panel supports drilldown.
The changes made here:
- When the root element is a subProcess, we assume it is a collapsed subprocess
- Process Variable discovery also works for collapsed subprocess planes

Add support for bpmn-js 9

---

CHANGELOG.md

chore(CHANGELOG): update breaking changes

---

src/provider/bpmn/properties/NameProps.js
test/spec/provider/bpmn/NameProps.bpmn
test/spec/provider/bpmn/NameProps.spec.js

don't display Name field for `bpmn:Association`

---

src/icons/bpmn-icon-association.svg
src/icons/bpmn-icon-data-input-output-association.svg
src/icons/index.js

Add missing connection icons to panel header

---

src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js
src/provider/camunda-platform/properties/FormDataProps.js
src/provider/camunda-platform/properties/FormTypeProps.js
test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider-Process.bpmn
test/spec/provider/camunda-platform/FormDataProps.bpmn
test/spec/provider/camunda-platform/FormDataProps.spec.js
test/spec/provider/camunda-platform/FormProps.bpmn
test/spec/provider/camunda-platform/FormTypeProps.spec.js

Closes camunda/camunda-modeler/issues/2496
https://user-images.githubusercontent.com/25825387/152951712-876cdde1-a051-4416-8591-0aa20ab3ce10.mov

refactor: include generated task forms in form select

---

package-lock.json
package.json

Follow up of https://github.com/camunda/camunda-bpmn-moddle/pull/95.

deps: bump camunda-bpmn-moddle

---

src/provider/zeebe/properties/BusinessRuleImplementationProps.js
test/spec/provider/zeebe/BusinessRuleImplementationProps.spec.js

fix(zeebe): set dmn implementation default as <none>

---

src/provider/camunda-platform/properties/ImplementationTypeProps.js
test/spec/provider/camunda-platform/ImplementationTypeProps.spec.js

feat(platform): reorder select options for implementationProps

---

src/provider/zeebe/properties/BusinessRuleImplementationProps.js
src/provider/zeebe/properties/CalledDecisionProps.js
test/spec/provider/zeebe/BusinessRuleImplementationProps.spec.js
test/spec/provider/zeebe/CalledDecisionProps.spec.js
test/spec/provider/zeebe/ZeebePropertiesProvider.spec.js

fix(zeebe): delete calledDecision for <none> dmn implementation

---

src/provider/zeebe/properties/MessageProps.js
test/spec/provider/zeebe/MessageProps.bpmn
test/spec/provider/zeebe/MessageProps.spec.js

related to https://camunda.slack.com/archives/GP70M0J6M/p1648052322348169

fix(zeebe): allow selection of message start event

---

package-lock.json
package.json

deps: bump to @bpmn-io/properties-panel@0.13.0

---

src/provider/camunda-platform/properties/ConditionProps.js
test/spec/provider/camunda-platform/ConditionProps.bpmn
test/spec/provider/camunda-platform/ConditionProps.spec.js

related to https://github.com/camunda/camunda-modeler/issues/2866
Old Properties Panel for reference:

fix(camunda-platform): add conditionalVariableName prop

---

CHANGELOG.md

* `FEAT`: add show callbacks to show erro code and message name errors ([#654](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/654))

chore(CHANGELOG): update to v1.0.0-alpha.11

---

src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js

Related to https://github.com/camunda/camunda-modeler/issues/2680

chore: rearrange process props by relevance

---

src/provider/cloud-element-templates/cmd/ChangeElementTemplateHandler.js
test/spec/provider/cloud-element-templates/cmd/ChangeElementTemplateHandler.spec.js

fix(cloud-templates): only keep defined mappings

---

src/contextProvider/zeebe/DescriptionProvider.js

chore(descriptionProvider): add description to decisionId field

---

src/provider/element-templates/util/templateUtil.js
test/spec/provider/cloud-element-templates/ElementTemplatesPropertiesProvider.spec.js
test/spec/provider/cloud-element-templates/fixtures/template-util.bpmn
test/spec/provider/cloud-element-templates/fixtures/template-util.json
test/spec/provider/cloud-element-templates/util/templateUtil.spec.js
test/spec/provider/element-templates/ElementTemplatesPropertiesProvider.spec.js
test/spec/provider/element-templates/fixtures/template-util.bpmn
test/spec/provider/element-templates/fixtures/template-util.json
test/spec/provider/element-templates/util/templateUtil.spec.js

fix(templates): keep element name after remove

---

CHANGELOG.md

chore(CHANGELOG): update to v1.0.0 👿  ➡️ 

---

README.md

docs: update properties provider usage

---

CHANGELOG.md

* `deps`: add `camunda-bpmn-js-behaviors` dependency ([#671](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/671))

chore(CHANGELOG): update to v1.1.0

---

CHANGELOG.md

Prepares us for the v1.1.1 release.

chore(CHANGELOG): update to v1.1.1

---

package-lock.json
package.json
src/icons/bpmn-empty-state.svg
src/icons/bpmn-multiple-state.svg
src/render/BpmnPropertiesPanel.js
src/render/PanelPlaceholderProvider.js
test/spec/BpmnPropertiesPanel.spec.js
test/test.css

Related to https://github.com/bpmn-io/properties-panel/issues/69
```sh
npx @bpmn-io/sr "bpmn-io/bpmn-js-properties-panel#use-updated-placeholder"
```

Add multiple selection state

---

package.json

deps: update `properties-panel` peer-dependency

---

.github/workflows/CI.yml
test/TestHelper.js
test/spec/BpmnPropertiesPanel.spec.js

It makes it possible to test with different properties panel versions (as we already do with `bpmn-js`).

Add `withPropertiesPanel` helper

---

package-lock.json
package.json

Just some cleanups I made during development.
```sh
npm audit fix
```

deps: fix audit errors

---

assets/element-templates.css

style(elementTemplates): override sticky header position

---

src/provider/camunda-platform/properties/ListenerProps.js
test/spec/provider/camunda-platform/FieldInjectionProps.spec.js
test/spec/provider/camunda-platform/FieldInjectonProps.bpmn

Related to https://github.com/camunda/camunda-modeler/issues/2989

fix: pass element in listener field injections

---

CHANGELOG.md

chore(CHANGELOG): update to v1.2.0

---

src/contextProvider/zeebe/DescriptionProvider.js

These doc links currently redirect but should be kept up-to-date.
There is no issue associated with this PR.

chore(description-provider): update links to docs

---

CHANGELOG.md

* `FEAT`: set errors through context ([#160](https://github.com/bpmn-io/properties-panel/pull/160))
* `DEPS`: update to `@bpmn-io/properties-panel@0.16.0`
* `DEPS`: update to `bpmn-js@9.3.0`

chore(CHANGELOG): update to v1.3.0

---

.github/workflows/CI.yml
package-lock.json
package.json
src/provider/cloud-element-templates/properties/CustomProperties.js
src/provider/zeebe/properties/AssignmentDefinitionProps.js
src/provider/zeebe/properties/CalledDecisionProps.js
src/provider/zeebe/properties/ConditionProps.js
src/provider/zeebe/properties/InputOutputParameter.js
src/provider/zeebe/properties/MessageProps.js
src/provider/zeebe/properties/MultiInstanceProps.js
src/provider/zeebe/properties/TargetProps.js
src/provider/zeebe/properties/TaskDefinitionProps.js
src/provider/zeebe/properties/TimerProps.js
test/TestHelper.js
test/spec/provider/zeebe/AssignmentDefinitionProps.spec.js
test/spec/provider/zeebe/ConditionProps.bpmn
test/spec/provider/zeebe/ConditionProps.spec.js
test/spec/provider/zeebe/InputOutputParameter.spec.js
test/spec/provider/zeebe/MessageProps.bpmn
test/spec/provider/zeebe/MessageProps.spec.js
test/spec/provider/zeebe/MultiInstanceProps.bpmn
test/spec/provider/zeebe/MultiInstanceProps.spec.js
test/spec/provider/zeebe/ZeebePropertiesProvider.spec.js

requires https://github.com/bpmn-io/properties-panel/pull/158
and https://github.com/bpmn-io/feel-editor/pull/8

feat: use FEEL fields

---

package-lock.json
package.json
src/provider/HOCs/index.js
src/provider/HOCs/withVariableContext.js
src/provider/cloud-element-templates/properties/CustomProperties.js
src/provider/zeebe/properties/AssignmentDefinitionProps.js
src/provider/zeebe/properties/CalledDecisionProps.js
src/provider/zeebe/properties/ConditionProps.js
src/provider/zeebe/properties/InputOutputParameter.js
src/provider/zeebe/properties/MessageProps.js
src/provider/zeebe/properties/MultiInstanceProps.js
src/provider/zeebe/properties/TargetProps.js
src/provider/zeebe/properties/TaskDefinitionProps.js
src/provider/zeebe/properties/TimerProps.js
test/spec/provider/HOCs/withVariableContext.bpmn
test/spec/provider/HOCs/withVariableContext.spec.js

Integration of https://github.com/bpmn-io/feel-editor/issues/3 into the properties panel.
try it out with `npm start`

feat(FEEL): pass variables to FEEL entries

---

src/provider/zeebe/properties/InputProps.js
src/provider/zeebe/properties/OutputProps.js

fix(input/output): remove whitespace in feel expression

---

CHANGELOG.md

chore(CHANGELOG): update to v1.4.0

---

package-lock.json
package.json

deps: bump to zeebe-bpmn-moddle@0.12.2

---

CHANGELOG.md
package-lock.json
package.json

Prepare 1.5.0 release

---

src/provider/cloud-element-templates/cmd/ChangeElementTemplateHandler.js
src/provider/cloud-element-templates/util/propertyUtil.js
test/spec/provider/cloud-element-templates/cmd/ChangeElementTemplateHandler.spec.js
test/spec/provider/cloud-element-templates/cmd/task-template-header-empty.json
test/spec/provider/cloud-element-templates/fixtures/condition.json
test/spec/provider/cloud-element-templates/properties/CustomProperties.spec.js

Do not serialize empty `zeebe:header` values

---

src/provider/zeebe/properties/ConditionProps.js
test/spec/provider/zeebe/ConditionProps.bpmn
test/spec/provider/zeebe/ConditionProps.spec.js

* show conditions group if source is inclusive gateway
---
Related https://github.com/camunda/camunda-modeler/issues/3083

feat(zeebe): show conditions group if source is inclusive gateway

---

test/spec/BpmnPropertiesPanelRenderer.spec.js

Verifies https://github.com/bpmn-io/properties-panel/pull/182.
---
Requires https://github.com/bpmn-io/properties-panel/pull/182

test: verify focus on showError

---

src/provider/zeebe/properties/InputProps.js
src/provider/zeebe/properties/OutputProps.js

related to https://github.com/camunda/camunda-modeler/issues/3073

chore(zeebe/In-Output): remove default source

---

src/provider/cloud-element-templates/util/propertyUtil.js
test/spec/provider/cloud-element-templates/ElementTemplateConditionChecker.spec.js
test/spec/provider/cloud-element-templates/fixtures/condition.json

related to https://github.com/camunda/camunda-modeler/issues/3140

fix(cloud-templates): allow adding properties without default value

---

src/provider/zeebe/properties/TimerProps.js
test/spec/provider/bpmn/TimerProps.spec.js
test/spec/provider/camunda-platform/TimerProps.spec.js
test/spec/provider/zeebe/TimerProps.spec.js

fix: unset correctly timer type

---

src/provider/cloud-element-templates/cmd/ChangeElementTemplateHandler.js
test/spec/provider/cloud-element-templates/ElementTemplates.spec.js
test/spec/provider/cloud-element-templates/cmd/ChangeElementTemplateHandler.spec.js
test/spec/provider/cloud-element-templates/cmd/task-template-1-dropdown.json
test/spec/provider/cloud-element-templates/fixtures/integration.bpmn
test/spec/provider/cloud-element-templates/fixtures/integration.json
test/spec/provider/element-templates/ElementTemplates.spec.js

closes https://github.com/bpmn-io/bpmn-js-properties-panel/issues/767

fix(cloud-templates): add replace rules for dropdowns

---

CHANGELOG.md

* `FEAT`: add candidate users entry to assignment group ([#776](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/776))
* `DEPS`: update to `@bpmn-io/properties-panel@0.24.0`
* `DEPS`: update to `diagram-js@10.0.0`

chore(CHANGELOG): update to v1.11.0

---

.github/workflows/CI.yml

Verify properties panel still works with bpmn-js@10.

ci: test against bpmn-js@10

---

CHANGELOG.md
package-lock.json
package.json

related to https://github.com/bpmn-io/internal-docs/issues/687

Prepare 1.12.0 release

---

package-lock.json
package.json

Closes https://github.com/bpmn-io/bpmn-js-properties-panel/issues/810

deps: update to `@bpmn-io/properties-panel@1.0.1`

---

src/provider/zeebe/ZeebePropertiesProvider.js
src/provider/zeebe/properties/ScriptImplementationProps.js
src/provider/zeebe/properties/ScriptProps.js
src/provider/zeebe/properties/index.js
src/provider/zeebe/utils/InputOutputUtil.js
src/provider/zeebe/utils/ZeebeServiceTaskUtil.js
test/spec/provider/zeebe/CalledDecisionProps.bpmn
test/spec/provider/zeebe/CalledDecisionProps.spec.js
test/spec/provider/zeebe/ScriptImplementationProps.bpmn
test/spec/provider/zeebe/ScriptImplementationProps.spec.js
test/spec/provider/zeebe/ScriptProps.bpmn
test/spec/provider/zeebe/ScriptProps.spec.js
test/spec/provider/zeebe/TaskDefinitionProps.bpmn
test/spec/provider/zeebe/TaskDefinitionProps.spec.js
test/spec/provider/zeebe/ZeebePropertiesProvider.bpmn
test/spec/provider/zeebe/ZeebePropertiesProvider.spec.js

Implement script task as a FEEL expression

---

package-lock.json
package.json
src/provider/HOCs/withVariableContext.js
src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js
src/provider/camunda-platform/properties/ProcessVariablesProps.js
test/TestHelper.js
test/spec/provider/HOCs/withVariableContext.spec.js
test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider.spec.js
test/spec/provider/camunda-platform/ProcessVariablesProps.spec.js

This PR bumps @bpmn-io/extract-process-variables and ensures that we handle asynchronous extractors correctly
related to https://github.com/bpmn-io/extract-process-variables/pull/24
related to https://github.com/bpmn-io/internal-docs/issues/680

deps: update to @bpmn-io/extract-process-variables@0.7.0

---

src/provider/HOCs/withVariableContext.js
test/spec/provider/HOCs/withVariableContext.spec.js

related to https://github.com/camunda/camunda-modeler/issues/3392

fix(VariableContext): don't stop propagation of events

---

src/provider/zeebe/properties/BusinessRuleImplementationProps.js
test/spec/provider/zeebe/BusinessRuleImplementationProps.spec.js

fix: remove task headers when implementation set to none

---

src/provider/cloud-element-templates/properties/CustomProperties.js
test/spec/provider/cloud-element-templates/fixtures/undefined-values-optional.json
test/spec/provider/cloud-element-templates/properties/CustomProperties.bpmn
test/spec/provider/cloud-element-templates/properties/CustomProperties.json
test/spec/provider/cloud-element-templates/properties/CustomProperties.spec.js

Add option to clear optional dropdown

---

CHANGELOG.md
src/provider/zeebe/properties/ErrorProps.js
test/spec/provider/zeebe/ErrorProps.bpmn
test/spec/provider/zeebe/ErrorProps.spec.js

Related to https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/74

Use FEEL editor for error code in throw events only

---

CHANGELOG.md
src/provider/zeebe/ZeebePropertiesProvider.js
src/provider/zeebe/properties/EscalationProps.js
src/provider/zeebe/properties/index.js
test/spec/provider/zeebe/EscalationProps.bpmn
test/spec/provider/zeebe/EscalationProps.spec.js
test/spec/provider/zeebe/ZeebePropertiesProvider.bpmn
test/spec/provider/zeebe/ZeebePropertiesProvider.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/3318

feat: allow escalation code to be a FEEL expression

---

package-lock.json
package.json

ensures that script result variables are available in the process 
related to https://github.com/bpmn-io/extract-process-variables/issues/25

deps: bump to @bpmn-io/extract-process-variables@0.8.0

---

src/provider/shared/ExtensionPropertiesProps.js
test/spec/provider/shared/ExtensionPropertiesProps.camunda.bpmn
test/spec/provider/shared/ExtensionPropertiesProps.spec.js
test/spec/provider/shared/ExtensionPropertiesProps.zeebe.bpmn

Related to https://github.com/camunda/camunda-modeler/issues/3417

fix(shared): removal of extension properties for `bpmn:Participant`

---

package-lock.json
package.json
test/spec/provider/cloud-element-templates/Validator.spec.js
test/spec/provider/cloud-element-templates/fixtures/error-invalid-optional.json
test/spec/provider/cloud-element-templates/fixtures/optional-valid.json

closes https://github.com/bpmn-io/bpmn-js-properties-panel/issues/840

feat: Support `optional` for `zeebe:taskHeader` bindings

---

src/provider/cloud-element-templates/Condition.js
src/provider/cloud-element-templates/create/TemplateElementFactory.js
test/spec/provider/cloud-element-templates/create/TemplateElementFactory.conditions.json
test/spec/provider/cloud-element-templates/create/TemplateElementFactory.spec.js

Related to https://github.com/bpmn-io/internal-docs/issues/718
The explanation of this approach is [here](https://github.com/bpmn-io/internal-docs/issues/718#issuecomment-1423938684)

fix(cloud-element-templates): `createElement` conditional props

---

package-lock.json
package.json
src/provider/HOCs/withVariableContext.js
test/spec/provider/HOCs/withVariableContext.spec.js

related to https://github.com/bpmn-io/internal-docs/issues/680

feat: use `variablesResolver` service, when available

---

CHANGELOG.md

chore(CHANGELOG): update to v1.18.0

---

src/provider/zeebe/properties/ScriptProps.js
test/spec/provider/zeebe/ScriptProps.spec.js

related to https://github.com/camunda/camunda-modeler/issues/3495

chore(zeebe/ScriptProps): move resultVariable to top

---

src/provider/zeebe/ZeebePropertiesProvider.js
src/provider/zeebe/properties/TaskScheduleProps.js
src/provider/zeebe/properties/index.js
test/spec/provider/zeebe/TaskScheduleProps.bpmn
test/spec/provider/zeebe/TaskScheduleProps.spec.js

---
Requires https://github.com/camunda/camunda-bpmn-js-behaviors/pull/34
Related to https://github.com/camunda/camunda-modeler/issues/3484

Support Due and Follow Up Date

---

CHANGELOG.md

* `FEAT`: add Due date and Follow up date properties ([#889](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/889))
* `CHORE`: update to `camunda-bpmn-js-behaviors@0.5.0`
* `CHORE`: update to `zeebe-bpmn-moddle@0.18.0`

chore(CHANGELOG): update to v1.20.0

---

README.md

* link C7 and C8 documentation
* mention + link element templates

docs: improve features

---

CHANGELOG.md

chore(CHANGELOG): update to v1.22.1

---

CHANGELOG.md

chore(CHANGELOG): update to v1.20.2

---

src/entries/FeelEntryWithContext.js
src/provider/cloud-element-templates/properties/CustomProperties.js
src/provider/zeebe/properties/AssignmentDefinitionProps.js
src/provider/zeebe/properties/CalledDecisionProps.js
src/provider/zeebe/properties/ConditionProps.js
src/provider/zeebe/properties/ErrorProps.js
src/provider/zeebe/properties/EscalationProps.js
src/provider/zeebe/properties/InputOutputParameter.js
src/provider/zeebe/properties/MessageProps.js
src/provider/zeebe/properties/MultiInstanceProps.js
src/provider/zeebe/properties/ScriptProps.js
src/provider/zeebe/properties/TargetProps.js
src/provider/zeebe/properties/TaskDefinitionProps.js
src/provider/zeebe/properties/TaskScheduleProps.js
src/provider/zeebe/properties/TimerProps.js

This prevents us from providing bogus suggestions.
Related to https://github.com/camunda/camunda-modeler/issues/3525
----

Only variable complete fields backed by IO mappings

---

src/provider/cloud-element-templates/ReplaceBehavior.js
test/spec/provider/cloud-element-templates/ElementTemplates.spec.js
test/spec/provider/cloud-element-templates/ReplaceBehavior.spec.js
test/spec/provider/cloud-element-templates/fixtures/start-event.json

fix: do not unlink template for none start event

---

CHANGELOG.md

Related to https://github.com/camunda/camunda-modeler/issues/3555

chore(CHANGELOG): update to v1.23.0

---

package-lock.json
package.json
src/provider/cloud-element-templates/properties/CustomProperties.js
test/spec/provider/cloud-element-templates/properties/CustomProperties.json
test/spec/provider/cloud-element-templates/properties/CustomProperties.spec.js

related to https://github.com/camunda/camunda-modeler/issues/3567

feat: validate `dropdown` and `textarea` custom entries

---

src/provider/cloud-element-templates/ReferencedElementBehavior.js
test/spec/provider/cloud-element-templates/ReferencedElementBehavior.spec.js

fix: unlink templated message instead of removing

---

CHANGELOG.md
src/provider/camunda-platform/properties/ConditionProps.js
test/spec/provider/camunda-platform/ConditionProps.bpmn
test/spec/provider/camunda-platform/ConditionProps.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/3568

fix: configure variable events for conditional start event

---

CHANGELOG.md
package-lock.json
package.json

chore: prepare 1.24.0

---

CHANGELOG.md
src/provider/cloud-element-templates/properties/CustomProperties.js
test/spec/provider/cloud-element-templates/properties/CustomProperties.bpmn
test/spec/provider/cloud-element-templates/properties/CustomProperties.json
test/spec/provider/cloud-element-templates/properties/CustomProperties.spec.js

Related to https://camunda.slack.com/archives/CKGH9LR40/p1684417089472889

fix: handle `undefined` values in custom properties validator

---

src/render/BpmnPropertiesPanel.js
test/spec/BpmnPropertiesPanel.spec.js

related to https://github.com/camunda/camunda-modeler/issues/3601#issuecomment-1540254176

fix(render): only call `layoutChanged` once per update

---

CHANGELOG.md

chore(CHANGELOG): update to 1.25.0

---

CHANGELOG.md

chore(CHANGELOG): update to v2.1.0

---

.github/workflows/CI.yml
CHANGELOG.md
package-lock.json
package.json
src/provider/bpmn/properties/IdProps.js
src/provider/bpmn/properties/ProcessProps.js

Also integrates the changed validation handling.
Closes #879

deps: update to properties-panel@3

---

.github/workflows/CI.yml
CHANGELOG.md
package-lock.json
package.json
src/contextProvider/zeebe/TooltipProvider.js
src/contextProvider/zeebe/index.js
src/index.js
src/provider/bpmn/properties/TimerProps.js
src/provider/camunda-platform/properties/TimerProps.js
src/provider/zeebe/properties/OutputPropagationProps.js
src/provider/zeebe/properties/TimerProps.js
src/render/BpmnPropertiesPanel.js
src/render/BpmnPropertiesPanelRenderer.js
test/TestHelper.js
test/spec/BpmnPropertiesPanel.spec.js
test/spec/BpmnPropertiesPanelRenderer.spec.js
test/spec/provider/zeebe/ErrorProps.spec.js
test/spec/provider/zeebe/EscalationProps.spec.js
test/spec/provider/zeebe/MessageProps.spec.js
test/spec/provider/zeebe/SignalProps.spec.js
test/spec/provider/zeebe/TaskDefinitionProps.spec.js

Add tooltips

---

CHANGELOG.md
package-lock.json
package.json

Update properties panel

---

CHANGELOG.md

chore(CHANGELOG): update to 5.0.0

---

package-lock.json
package.json

chore: update dependency zeebe-bpmn-moddle to 1.0.0

---

CHANGELOG.md

chore(CHANGELOG): update to v5.1.0

---

src/contextProvider/zeebe/TooltipProvider.js
src/provider/zeebe/properties/TaskDefinitionProps.js
test/spec/provider/zeebe/MessageProps.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/3611

Improve tooltips

---

CHANGELOG.md

In order to finish https://github.com/camunda/camunda-modeler/issues/3611

chore(CHANGELOG): update to v5.2.0

---

CHANGELOG.md

This adds a previously "under the radar" major addition.

chore(CHANGELOG): add FEEL popup menu entry

---

CHANGELOG.md
package-lock.json
package.json
src/render/BpmnPropertiesPanel.js
src/render/BpmnPropertiesPanelRenderer.js
test/spec/BpmnPropertiesPanelRenderer.spec.js

Use via
```js
propertiesPanel: {
feelPopupContainer: ...
}
```
Follow up of https://github.com/bpmn-io/properties-panel/pull/280

feat(feel-popup): provide container for feel popup editors

---

.github/workflows/CI.yml

chore: target node v20

---

CHANGELOG.md
package-lock.json
package.json

Update to v5.3.0, incorporating latest properties-panel fixes.

Prepare v5.3.0

---

.github/workflows/CI.yml
test/TestHelper.js

Housekeeping

---

CHANGELOG.md
package-lock.json
package.json
test/spec/provider/zeebe/ScriptImplementationProps.spec.js

https://github.com/bpmn-io/properties-panel/compare/v3.7.1...v3.8.0

Integrate properties-panel 3.8.0

---

CHANGELOG.md
package-lock.json
package.json

deps: update to `@bpmn-io/properties-panel@3.11.0`

---

package-lock.json
package.json
src/provider/zeebe/properties/FormProps.js
src/provider/zeebe/utils/FormUtil.js
src/utils/ElementUtil.js
src/utils/ExtensionElementsUtil.js
test/spec/provider/zeebe/Forms.bpmn
test/spec/provider/zeebe/Forms.spec.js

* add _Camunda form (linked)_ option to _Type_ select
* add _Form ID_ input
* refactorings
---
Closes #949
Depends on https://github.com/camunda/camunda-bpmn-js-behaviors/pull/49

Support Linked Camunda Form

---

package-lock.json
package.json

Clean dependencies

---

src/provider/zeebe/properties/FormProps.js

chore: capitalize "Camunda Forms"

---

README.md

fix(README): fix Camunda properties docs

---

src/provider/zeebe/properties/InputPropagationProps.js

Related to https://github.com/camunda/camunda-modeler/issues/4051

chore(zeebe): align input propagation label and tooltip

---

CHANGELOG.md
package-lock.json
package.json

Update properties panel to v3.16

---

src/contextProvider/zeebe/TooltipProvider.js

Closes #1032
---
The tooltip content is inspired by the script task implementation tooltip.

feat: add user task implementation tooltip

---

src/contextProvider/zeebe/TooltipProvider.js

Related to https://github.com/camunda/camunda-modeler/issues/4183

feat: update form section tooltip

---

package-lock.json
package.json
rollup.config.mjs

Clean dist

---

src/provider/zeebe/ZeebePropertiesProvider.js
src/render/BpmnPropertiesPanel.js
src/render/PanelHeaderProvider.js
test/spec/PanelHeaderProvider.spec.js

fix: add missing translations in header and tab labels

---

src/contextProvider/zeebe/TooltipProvider.js

Add called decision guidance

---

src/provider/camunda-platform/properties/ProcessProps.js
test/spec/provider/camunda-platform/ProcessProps.bpmn
test/spec/provider/camunda-platform/ProcessProps.spec.js

Related to https://github.com/camunda/camunda-modeler/issues/4317

fix: display process name only once for C7

---

karma.config.js

The code coverage is currently not collected at all. This PR fixes the problem.

test: fix code coverage report

---

CHANGELOG.md
package-lock.json
package.json

Closes #713
Related to https://github.com/camunda/camunda-modeler/issues/3660
Update to @bpmn-io/properties-panel@3.23.0

deps: update to @bpmn-io/properties-panel@3.23.0

---

CHANGELOG.md

* `FEAT`: add _Priority_ entry to user task _Assignment_ group ([#1072](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1072))

chore(CHANGELOG): update to v5.22.0

---

src/contextProvider/zeebe/TooltipProvider.js
src/provider/zeebe/properties/UserTaskImplementationProps.js

Related to https://github.com/camunda/camunda-modeler/issues/4749

chore: update terminology to "camunda user task"

---

src/provider/zeebe/properties/TaskListener.js

Related to https://github.com/camunda/camunda-modeler/issues/4798

feat: add `updating` task listener event type

---

CHANGELOG.md
package-lock.json
package.json

Includes:
* `FIX`: add focus to checkboxes and buttons ([bpmn-io/properties-panel#390](https://github.com/bpmn-io/properties-panel/pull/390))
* `FIX`: remove input border from popups ([bpmn-io/properties-panel#398](https://github.com/bpmn-io/properties-panel/pull/398))
* `FIX`: make tooltip persist when trying to copy from it ([bpmn-io/properties-panel#399](https://github.com/bpmn-io/properties-panel/pull/399))

deps: update to @bpmn-io/properties-panel@3.26.2

---

CHANGELOG.md
package-lock.json
package.json

update deps to include feel updates (unclosed string detection, multiline strings)

deps: update to @bpmn-io/properties-panel@3.33.0
